#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT = ROOT / "main.lua"
ORDER = [
    "engine.lua", "stage_data.lua", "sprites.lua", "audio.lua", "save.lua",
    "world.lua", "debug.lua", "render.lua", "game.lua", "99_entry.lua",
]
BANNED_RUNTIME = ("require(", "dofile(", "loadfile(")

def main():
    chunks = [
        "-- CatBoxMRE production bundle\n",
        "-- Generated by tools/bundle_main.py. Edit src/*.lua, not this file.\n",
        "-- Lua 5.1-compatible; no runtime module loader.\n\n",
    ]
    for name in ORDER:
        path = SRC / name
        if not path.exists():
            raise SystemExit("Missing module: " + str(path))
        text = path.read_text(encoding="utf-8")
        # Low-memory production: drop blank and full-line comment lines.
        text = "\n".join(line.strip() for line in text.splitlines() if line.strip() and not line.lstrip().startswith("--"))
        chunks.append(text + "\n")
    bundled = "".join(chunks)
    compact = bundled.replace(" ", "")
    for token in BANNED_RUNTIME:
        if token in compact:
            raise SystemExit("Production bundle contains forbidden loader: " + token)
    OUT.write_text(bundled, encoding="utf-8", newline="\n")
    print("[OK] Wrote", OUT, "(%d bytes)" % OUT.stat().st_size)

if __name__ == "__main__":
    main()
