-- CatBoxMRE production bundle
-- Generated by tools/bundle_main.py. Edit src/*.lua, not this file.
-- Lua 5.1-compatible; no runtime module loader.

Engine = Engine or {}
Engine.W, Engine.H = 240, 320
Engine.keys = {}
Engine.time_ms = 0
Engine.host = nil
Engine.has_graphics = false
Engine.has_images = false
Engine.has_files = false
Engine._color_cache = {}
Engine.draw_count = 0
Engine.clear_count = 0
Engine.rect_count = 0
Engine.text_count = 0
Engine.flush_count = 0
Engine.boot_lines = {}
Engine.boot_line_count = 0
Engine.boot_log_path = "catbox_boot.log"
local host = nil
if type(engine) == "table" then
host = engine
elseif type(mre) == "table" then
host = mre
end
Engine.host = host
local function host_fn(name)
if type(host) == "table" and type(host[name]) == "function" then
return host[name]
end
return nil
end
Engine._clear = host_fn("clear")
Engine._rect = host_fn("rect")
Engine._text = host_fn("text")
Engine._flush = host_fn("flush")
Engine._color = host_fn("color")
Engine._image = host_fn("image")
Engine._image_region = host_fn("image_region")
Engine._tick_ms = host_fn("tick_ms")
Engine._exit = host_fn("exit")
Engine._file_read = host_fn("file_read")
Engine._file_write = host_fn("file_write")
Engine._memory_info = host_fn("memory_info")
Engine._set_font = host_fn("set_font")
Engine._log = host_fn("log")
Engine._tone = host_fn("play_tone") or host_fn("tone")
local function rgb565_manual(rgb)
if type(rgb) ~= "number" then return 0xFFFF end
if rgb <= 0xFFFF then return rgb end
local r = math.floor(rgb / 65536) % 256
local g = math.floor(rgb / 256) % 256
local b = rgb % 256
return math.floor(r / 8) * 2048 + math.floor(g / 4) * 32 + math.floor(b / 8)
end
function Engine.color(rgb)
if type(rgb) ~= "number" then return 0xFFFF end
if rgb <= 0xFFFF then return rgb end
local cached = Engine._color_cache[rgb]
if cached ~= nil then return cached end
local c = nil
if Engine._color then
local r = math.floor(rgb / 65536) % 256
local g = math.floor(rgb / 256) % 256
local b = rgb % 256
local ok, v = pcall(Engine._color, r, g, b)
if ok and type(v) == "number" then c = v end
end
if c == nil then c = rgb565_manual(rgb) end
Engine._color_cache[rgb] = c
return c
end
local function boot_dump()
if not Engine._file_write then return end
local text = ""
local i = 1
while i <= Engine.boot_line_count do
text = text .. Engine.boot_lines[i] .. "\n"
i = i + 1
end
pcall(Engine._file_write, Engine.boot_log_path, text)
end
function Engine.boot_log(msg)
msg = tostring(msg or "")
if Engine.boot_line_count < 16 then
Engine.boot_line_count = Engine.boot_line_count + 1
Engine.boot_lines[Engine.boot_line_count] = "[CatBox] " .. msg
end
if Engine._log then pcall(Engine._log, "[CatBox] " .. msg)
elseif type(print) == "function" then print("[CatBox] " .. msg) end
boot_dump()
end
function Engine.init()
Engine.has_graphics = Engine._rect ~= nil or Engine._clear ~= nil
local allow_images = true
if type(host) == "table" and host.has_images == false then allow_images = false end
Engine.has_images = allow_images and Engine._image_region ~= nil
Engine.has_files = Engine._file_read ~= nil and Engine._file_write ~= nil
if type(host) == "table" then
if type(host.W) == "number" then Engine.W = host.W end
if type(host.H) == "number" then Engine.H = host.H end
end
if Engine._set_font then pcall(Engine._set_font, 12) end
Engine.boot_log("ENGINE INIT gfx=" .. tostring(Engine.has_graphics) .. " img=" .. tostring(Engine.has_images) .. " files=" .. tostring(Engine.has_files))
end
function Engine.clear(color)
Engine.clear_count = Engine.clear_count + 1
local c = Engine.color(color or 0x000000)
if Engine._clear then
local ok = pcall(Engine._clear, c)
if ok then return true end
Engine._clear = nil
end
return Engine.rect(0, 0, Engine.W, Engine.H, color or 0x000000)
end
function Engine.rect(x, y, w, h, color)
if w <= 0 or h <= 0 then return true end
if not Engine._rect then return false end
Engine.rect_count = Engine.rect_count + 1
local ok = pcall(Engine._rect, math.floor(x), math.floor(y), math.floor(w), math.floor(h), Engine.color(color or 0xFFFFFF))
if not ok then Engine._rect = nil; Engine.has_graphics = Engine._clear ~= nil end
return ok
end
function Engine.text(x, y, s, color)
if not Engine._text then return false end
Engine.text_count = Engine.text_count + 1
local ok = pcall(Engine._text, math.floor(x), math.floor(y), tostring(s or ""), Engine.color(color or 0xFFFFFF))
if not ok then Engine._text = nil end
return ok
end
function Engine.flush()
Engine.flush_count = Engine.flush_count + 1
if not Engine._flush then return false end
local ok = pcall(Engine._flush)
if not ok then Engine._flush = nil end
return ok
end
function Engine.load_image(path)
if not Engine.has_images then return nil end
return tostring(path or "")
end
function Engine.image_region(img, sx, sy, sw, sh, dx, dy)
if not Engine.has_images or not Engine._image_region or not img then return false end
local ok, ret = pcall(Engine._image_region, img, sx, sy, sw, sh, math.floor(dx), math.floor(dy))
if not ok or ret == false then
Engine.has_images = false
Engine._image_region = nil
return false
end
return true
end
function Engine.play_tone(freq, ms)
if not Engine._tone then return false end
local ok, ret = pcall(Engine._tone, freq, ms)
return ok and ret ~= false
end
function Engine.file_read(path)
if not Engine._file_read then return nil end
local ok, value = pcall(Engine._file_read, tostring(path or ""))
if ok then return value end
return nil
end
function Engine.file_write(path, data)
if not Engine._file_write then return false end
local ok, value = pcall(Engine._file_write, tostring(path or ""), tostring(data or ""))
return ok and value ~= false
end
function Engine.exit()
if Engine._exit then pcall(Engine._exit) end
end
function Engine.memory_info()
if Engine._memory_info then
local ok, value = pcall(Engine._memory_info)
if ok then return value, true end
end
return collectgarbage("count"), false
end
function Engine.ticks()
if Engine._tick_ms then
local ok, value = pcall(Engine._tick_ms)
if ok and type(value) == "number" then return value end
end
return Engine.time_ms
end
local KEY_MAP = {
up="UP", down="DOWN", left="LEFT", right="RIGHT", ok="5",
softleft="SOFTLEFT", softright="SOFTRIGHT", lsk="SOFTLEFT", rsk="SOFTRIGHT",
clear="BACK", back="BACK", enter="5", ["return"]="5",
["0"]="0", ["1"]="1", ["2"]="2", ["3"]="3", ["4"]="4",
["5"]="5", ["6"]="6", ["7"]="7", ["8"]="8", ["9"]="9",
["*"]="*", ["#"]="#"
}
local function norm_key(k)
local s = tostring(k or "")
local low = string.lower(s)
return KEY_MAP[low] or string.upper(s)
end
function Engine.key_down(k)
local n = norm_key(k)
if n ~= "" then Engine.keys[n] = true end
end
function Engine.key_up(k)
local n = norm_key(k)
if n ~= "" then Engine.keys[n] = false end
end
function Engine.down(a, b)
return Engine.keys[norm_key(a)] or (b and Engine.keys[norm_key(b)]) or false
end
StageData = StageData or {}
StageData.stages = {
{name="Meadow Start",width=720,spawn={28,220},goal={676,220},solids={{0,260,180,36},{220,260,210,36},{470,260,250,36},{110,210,80,16},{300,198,92,16},{520,205,84,16}},coins={{70,238},{132,186},{164,186},{252,238},{320,174},{352,174},{500,238},{548,181},{580,181},{640,238}},keys={},hazards={},springs={},movers={},enemies={{"slug",360,240,70},{"slug",540,240,60}},boxes={},checkpoints={{250,236}},need_key=false,theme="meadow",decor={{"sign",210,236},{"bush",156,238},{"bush",560,238}}},
{name="Neighbor Yard",width=760,spawn={24,220},goal={718,212},solids={{0,260,136,36},{168,260,192,36},{398,260,162,36},{594,260,166,36},{80,210,84,16},{234,190,86,16},{450,198,86,16},{642,188,72,16}},coins={{52,238},{100,186},{190,238},{254,166},{286,166},{420,238},{474,174},{618,238},{664,164}},keys={{510,170}},hazards={{"spike",360,248,38,12}},springs={},movers={},enemies={{"slug",215,240,64}},boxes={},checkpoints={},need_key=true,theme="meadow",decor={{"house",675,228},{"sign",332,236}}},
{name="Box Lesson",width=800,spawn={20,220},goal={758,180},solids={{0,260,180,36},{230,260,120,36},{390,260,150,36},{600,230,200,66},{100,208,86,16},{430,198,88,16}},coins={{40,238},{128,184},{200,238},{250,238},{330,238},{408,238},{452,174},{620,206},{668,206},{718,206}},keys={},hazards={{"spike",180,248,48,12},{"spike",350,248,40,12}},springs={},movers={},enemies={{"slug",510,240,68}},boxes={{188,228,28,32},{545,228,28,32}},checkpoints={{405,236}},need_key=false,theme="boxland",decor={{"sign",156,236},{"fence",700,236}}},
{name="Spring Lesson",width=820,spawn={20,220},goal={778,170},solids={{0,260,150,36},{190,260,120,36},{350,230,110,66},{500,260,150,36},{690,210,130,86},{96,188,70,16},{240,150,80,16},{560,186,80,16}},coins={{46,238},{110,164},{210,238},{260,126},{380,206},{530,238},{590,162},{720,186},{758,186}},keys={},hazards={{"spike",310,248,40,12}},springs={{154,244,28,16,260},{658,244,28,16,275}},movers={},enemies={{"ghost",420,154,72}},boxes={},checkpoints={},need_key=false,theme="spring",decor={{"sign",144,236},{"sign",645,236}}},
{name="Moving Day",width=900,spawn={24,220},goal={850,220},solids={{0,260,130,36},{310,260,120,36},{570,260,130,36},{770,260,130,36},{80,205,70,16},{610,190,70,16}},coins={{48,238},{92,181},{176,190},{245,160},{340,238},{466,185},{600,166},{654,166},{736,195},{814,238}},keys={},hazards={},springs={},movers={{150,220,64,12,"x",110,80},{445,215,72,12,"y",70,55},{705,225,60,12,"x",95,70}},enemies={{"slug",345,240,54}},boxes={},checkpoints={},need_key=false,theme="moving",decor={{"sign",690,236},{"bush",620,238}}},
{name="Spike Alley",width=880,spawn={18,220},goal={842,180},solids={{0,260,220,36},{280,260,170,36},{510,260,180,36},{744,220,136,76},{120,205,70,16},{332,195,70,16},{560,185,90,16}},coins={{40,238},{142,181},{196,238},{310,238},{350,171},{532,238},{580,161},{620,161},{770,196},{820,196}},keys={},hazards={{"spike",220,248,60,12},{"spike",450,248,60,12},{"spike",690,248,52,12}},springs={},movers={},enemies={{"slug",380,240,55}},boxes={{226,228,28,32},{690,228,28,32}},checkpoints={{530,236}},need_key=false,theme="danger",decor={{"sign",296,236},{"sign",612,236}}},
{name="Ghost Garden",width=980,spawn={24,220},goal={936,198},solids={{0,260,150,36},{196,260,140,36},{388,260,120,36},{566,260,150,36},{770,238,210,58},{104,210,70,16},{248,178,70,16},{432,198,70,16},{610,174,80,16},{822,186,82,16}},coins={{44,238},{120,186},{212,238},{268,154},{402,238},{454,174},{586,238},{632,150},{680,150},{794,216},{840,162},{882,162},{942,216}},keys={},hazards={{"spike",336,248,52,12},{"spike",716,248,54,12}},springs={},movers={},enemies={{"ghost",330,132,80},{"ghost",650,120,74},{"slug",820,218,58}},boxes={},checkpoints={},need_key=false,theme="ghost",decor={{"bush",282,156},{"bush",854,166}}},
{name="Key and Lift",width=1040,spawn={22,220},goal={994,170},solids={{0,260,170,36},{240,260,145,36},{460,260,150,36},{700,260,140,36},{910,210,130,86},{95,206,72,16},{500,190,88,16},{748,188,70,16}},coins={{50,238},{110,182},{194,220},{275,238},{352,238},{485,166},{540,166},{630,215},{724,238},{770,164},{864,210},{936,186},{980,186}},keys={{548,158}},hazards={},springs={},movers={{178,220,56,12,"y",86,50},{400,220,54,12,"x",86,62},{620,220,62,12,"y",100,48},{850,220,54,12,"x",70,65}},enemies={},boxes={},checkpoints={},need_key=true,theme="moving",decor={{"sign",312,236},{"sign",706,236}}},
{name="Bubble Steps",width=1080,spawn={22,220},goal={1036,196},solids={{0,260,150,36},{220,242,100,54},{390,222,95,74},{560,202,100,94},{735,230,94,66},{905,238,175,58}},coins={{48,238},{122,238},{240,218},{290,218},{410,198},{455,198},{580,178},{628,178},{755,206},{800,206},{930,214},{980,214},{1030,214}},keys={},hazards={},springs={{168,244,28,16,250},{334,226,28,16,245},{500,206,28,16,245},{675,244,28,16,265},{848,244,28,16,250}},movers={},enemies={{"ghost",520,90,85},{"ghost",860,128,65}},boxes={},checkpoints={},need_key=false,theme="bubble",decor={{"bubble",120,100},{"bubble",160,88},{"bubble",198,102},{"bubble",840,82},{"bubble",892,92},{"bubble",940,86}}},
{name="Crusher Hall",width=940,spawn={24,220},goal={900,220},solids={{0,260,940,36},{118,200,110,16},{306,186,116,16},{506,205,110,16},{700,182,110,16}},coins={{48,238},{142,176},{180,176},{270,238},{330,162},{378,162},{470,238},{532,181},{580,181},{668,238},{726,158},{770,158},{854,238}},keys={},hazards={{"crusher",236,30,30,220},{"crusher",438,45,30,205},{"crusher",635,25,30,225},{"spike",280,248,24,12}},springs={},movers={},enemies={{"slug",520,240,60},{"ghost",760,126,60}},boxes={},checkpoints={},need_key=false,theme="danger",decor={{"sign",250,236},{"sign",462,236},{"sign",657,236}}},
{name="Danger Above",width=1140,spawn={20,220},goal={1095,220},solids={{0,260,1140,36},{110,210,82,16},{270,190,90,16},{455,210,95,16},{650,184,95,16},{852,205,90,16}},coins={{44,238},{128,186},{172,186},{238,238},{296,166},{336,166},{418,238},{474,186},{520,186},{615,238},{674,160},{716,160},{820,238},{872,181},{916,181},{1000,238},{1070,238}},keys={},hazards={{"crusher",205,20,32,224},{"crusher",382,25,32,219},{"crusher",566,18,32,226},{"crusher",764,36,32,208},{"crusher",960,22,32,222}},springs={},movers={},enemies={{"slug",500,240,60},{"slug",885,240,55}},boxes={},checkpoints={{620,236}},need_key=false,theme="danger",decor={{"sign",208,236},{"sign",765,236},{"sign",962,236}}},
{name="Cat Tower",width=1200,spawn={20,220},goal={1152,72},solids={{0,260,210,36},{260,230,100,66},{410,200,100,96},{560,170,100,126},{710,140,100,156},{860,110,100,186},{1010,82,190,214}},coins={{45,238},{120,238},{282,206},{330,206},{432,176},{480,176},{582,146},{630,146},{732,116},{780,116},{882,86},{930,86},{1036,58},{1080,58},{1130,58}},keys={},hazards={{"spike",210,248,50,12},{"spike",360,248,50,12},{"spike",510,248,50,12},{"spike",660,248,50,12},{"spike",810,248,50,12},{"spike",960,248,50,12}},springs={{220,244,28,16,260},{370,244,28,16,260},{520,244,28,16,260}},movers={},enemies={{"ghost",900,54,64}},boxes={},checkpoints={},need_key=false,theme="tower",decor={{"bubble",1060,46},{"bubble",1100,34}}},
{name="Final Picnic",width=1280,spawn={20,220},goal={1235,220},solids={{0,260,180,36},{230,260,190,36},{480,260,180,36},{720,260,180,36},{960,260,320,36},{100,205,70,16},{280,186,90,16},{520,194,84,16},{760,176,90,16},{1030,188,86,16}},coins={{42,238},{120,181},{200,220},{250,238},{304,162},{350,162},{450,220},{505,238},{542,170},{590,170},{688,220},{744,238},{782,152},{830,152},{930,220},{990,238},{1050,164},{1098,164},{1170,238},{1220,238}},keys={{1090,136}},hazards={{"spike",180,248,50,12},{"spike",420,248,60,12},{"spike",660,248,60,12},{"spike",900,248,60,12}},springs={},movers={{185,216,48,12,"y",70,52},{430,212,48,12,"x",80,62},{670,208,48,12,"y",75,50},{910,220,48,12,"x",86,58}},enemies={{"slug",340,240,60},{"ghost",610,132,70},{"slug",820,240,60},{"ghost",1120,116,60}},boxes={{995,228,28,32}},checkpoints={{970,236}},need_key=true,theme="meadow",decor={{"sign",1005,236},{"house",1180,228}}},
{name="Cloud Path",width=1320,spawn={20,220},goal={1276,170},solids={{0,260,180,36},{240,260,120,36},{420,260,110,36},{610,260,120,36},{810,260,140,36},{1010,230,120,66},{1190,210,130,86},{120,206,70,16},{300,180,74,16},{495,156,74,16},{700,182,78,16},{900,154,78,16},{1080,134,78,16}},coins={{40,238},{120,182},{190,238},{258,238},{320,156},{350,156},{440,238},{510,132},{545,132},{630,238},{720,158},{756,158},{830,238},{920,130},{956,130},{1036,206},{1100,110},{1138,110},{1240,186}},keys={},hazards={{"spike",182,248,58,12},{"spike",732,248,78,12}},springs={{575,244,28,16,260}},movers={},enemies={{"ghost",875,104,80},{"slug",1045,210,55}},boxes={},checkpoints={{660,236}},need_key=false,theme="cloud",decor={{"bubble",890,70},{"bubble",930,58},{"bubble",970,72}}},
{name="Pipe Parade",width=1360,spawn={18,220},goal={1316,220},solids={{0,260,150,36},{205,260,110,36},{370,260,110,36},{535,260,110,36},{700,260,110,36},{865,260,110,36},{1030,260,110,36},{1195,260,165,36},{100,222,70,16},{270,202,70,16},{440,222,70,16},{610,202,70,16},{780,222,70,16},{950,202,70,16},{1120,222,70,16}},coins={{40,238},{120,198},{228,238},{292,178},{396,238},{462,198},{560,238},{636,178},{728,238},{806,198},{894,238},{976,178},{1064,238},{1144,198},{1250,238},{1302,238}},keys={},hazards={{"spike",150,248,54,12},{"spike",315,248,54,12},{"spike",480,248,54,12},{"spike",645,248,54,12},{"spike",810,248,54,12},{"spike",975,248,54,12},{"spike",1140,248,54,12}},springs={{175,244,24,16,245},{340,244,24,16,245},{505,244,24,16,245},{670,244,24,16,245},{835,244,24,16,245},{1000,244,24,16,245}},movers={},enemies={{"ghost",560,110,60},{"ghost",1040,104,60}},boxes={},checkpoints={},need_key=false,theme="bubble",decor={{"pipe",182,242},{"pipe",347,242},{"pipe",512,242},{"pipe",677,242},{"pipe",842,242},{"pipe",1007,242}}},
{name="Ghost Lift",width=1420,spawn={18,220},goal={1370,170},solids={{0,260,170,36},{240,260,140,36},{460,260,150,36},{690,260,140,36},{920,260,150,36},{1160,220,260,76},{100,205,70,16},{500,182,90,16},{960,186,88,16},{1240,188,90,16}},coins={{42,238},{120,181},{196,238},{270,238},{338,238},{482,158},{528,158},{620,238},{714,238},{780,238},{942,162},{988,162},{1088,238},{1180,196},{1260,164},{1304,164}},keys={{555,150}},hazards={{"spike",380,248,78,12},{"spike",830,248,88,12}},springs={},movers={{176,220,54,12,"y",84,48},{394,220,54,12,"x",72,56},{628,220,54,12,"y",78,50},{850,220,54,12,"x",74,54},{1096,220,54,12,"y",78,50}},enemies={{"ghost",330,140,74},{"ghost",740,132,74},{"slug",1260,200,60}},boxes={},checkpoints={{690,236}},need_key=true,theme="ghost",decor={{"sign",328,236},{"sign",896,236}}},
{name="Canyon Box",width=1460,spawn={20,220},goal={1415,180},solids={{0,260,200,36},{270,260,150,36},{490,260,130,36},{690,260,160,36},{920,260,150,36},{1140,230,140,66},{1320,200,140,96},{120,210,70,16},{525,188,80,16},{950,180,90,16}},coins={{46,238},{130,186},{220,238},{292,238},{360,238},{508,164},{550,164},{640,238},{742,238},{800,238},{940,156},{988,156},{1078,238},{1168,206},{1210,206},{1362,176}},keys={},hazards={{"spike",200,248,70,12},{"spike",420,248,70,12},{"spike",620,248,70,12},{"spike",850,248,70,12},{"spike",1070,248,70,12}},springs={},movers={},enemies={{"slug",560,240,68},{"slug",980,240,68}},boxes={{214,228,28,32},{445,228,28,32},{875,228,28,32}},checkpoints={{760,236}},need_key=false,theme="boxland",decor={{"sign",300,236},{"sign",1090,236}}},
{name="Bubble Run",width=1500,spawn={18,220},goal={1450,160},solids={{0,260,150,36},{220,260,110,36},{390,260,110,36},{560,260,110,36},{730,260,110,36},{900,260,110,36},{1070,230,110,66},{1240,200,110,96},{1390,170,110,126}},coins={{42,238},{124,238},{240,238},{300,238},{408,238},{468,238},{580,238},{640,238},{748,238},{808,238},{920,238},{980,238},{1100,206},{1140,206},{1262,176},{1304,176},{1412,146},{1450,146}},keys={},hazards={{"spike",150,248,70,12},{"spike",330,248,60,12},{"spike",500,248,60,12},{"spike",670,248,60,12},{"spike",840,248,60,12},{"spike",1010,248,60,12}},springs={{186,244,28,16,255},{356,244,28,16,255},{526,244,28,16,255},{696,244,28,16,255},{866,244,28,16,255},{1036,244,28,16,255}},movers={},enemies={{"ghost",1175,120,80}},boxes={},checkpoints={},need_key=false,theme="bubble",decor={{"bubble",1110,62},{"bubble",1160,56},{"bubble",1210,70},{"bubble",1260,64}}},
{name="Stair Hop",width=1540,spawn={18,220},goal={1492,140},solids={{0,260,180,36},{250,230,110,66},{430,200,110,96},{610,170,110,126},{790,140,110,156},{970,170,110,126},{1150,200,110,96},{1330,230,210,66}},coins={{46,238},{130,238},{272,206},{320,206},{452,176},{500,176},{632,146},{680,146},{812,116},{860,116},{992,146},{1040,146},{1172,176},{1220,176},{1360,206},{1410,206},{1490,116}},keys={{844,92}},hazards={{"spike",180,248,70,12},{"spike",360,248,70,12},{"spike",540,248,70,12},{"spike",720,248,70,12},{"spike",900,248,70,12},{"spike",1080,248,70,12},{"spike",1260,248,70,12}},springs={{220,244,28,16,260},{400,244,28,16,260},{580,244,28,16,260},{760,244,28,16,260}},movers={},enemies={{"ghost",1000,102,64}},boxes={},checkpoints={{790,236}},need_key=true,theme="tower",decor={{"sign",218,236},{"sign",760,236}}},
{name="Key Canyon",width=1600,spawn={18,220},goal={1554,200},solids={{0,260,160,36},{230,260,130,36},{430,260,110,36},{620,260,130,36},{830,260,120,36},{1020,260,130,36},{1230,260,140,36},{1460,220,140,76},{100,205,72,16},{300,180,72,16},{490,152,72,16},{690,180,72,16},{900,148,72,16},{1090,176,72,16},{1280,148,72,16}},coins={{40,238},{118,181},{180,238},{248,238},{318,156},{352,156},{448,238},{508,128},{542,128},{640,238},{708,156},{742,156},{848,238},{918,124},{952,124},{1040,238},{1114,152},{1148,152},{1250,238},{1308,124},{1342,124},{1500,196}},keys={{920,116}},hazards={{"spike",160,248,70,12},{"spike",360,248,70,12},{"spike",540,248,80,12},{"spike",750,248,80,12},{"spike",950,248,70,12},{"spike",1150,248,80,12},{"spike",1370,248,90,12}},springs={},movers={{556,220,50,12,"x",64,56},{770,220,50,12,"x",60,58},{1180,220,50,12,"y",80,50}},enemies={{"slug",680,240,55},{"ghost",1220,102,70}},boxes={{970,228,28,32}},checkpoints={{840,236}},need_key=true,theme="danger",decor={{"sign",520,236},{"sign",1408,236}}},
{name="Ghost Ceiling",width=1640,spawn={18,220},goal={1590,90},solids={{0,260,210,36},{290,230,110,66},{470,200,110,96},{650,170,110,126},{830,170,110,126},{1010,200,110,96},{1190,230,110,66},{1370,110,270,186}},coins={{46,238},{130,238},{314,206},{360,206},{492,176},{540,176},{674,146},{720,146},{854,146},{900,146},{1034,176},{1080,176},{1214,206},{1260,206},{1400,86},{1450,86},{1500,86},{1560,86}},keys={},hazards={{"spike",210,248,80,12},{"spike",400,248,70,12},{"spike",580,248,70,12},{"spike",760,248,70,12},{"spike",940,248,70,12},{"spike",1120,248,70,12},{"spike",1300,248,70,12}},springs={{264,244,28,16,265},{444,244,28,16,265},{624,244,28,16,265},{804,244,28,16,265},{984,244,28,16,265}},movers={},enemies={{"ghost",510,124,72},{"ghost",860,110,74},{"ghost",1200,132,74}},boxes={},checkpoints={},need_key=false,theme="ghost",decor={{"bubble",1420,56},{"bubble",1470,48},{"bubble",1520,62}}},
{name="Tower Return",width=1680,spawn={18,220},goal={1632,70},solids={{0,260,210,36},{260,230,100,66},{410,200,100,96},{560,170,100,126},{710,140,100,156},{860,110,100,186},{1010,82,100,214},{1160,82,100,214},{1310,82,100,214},{1460,82,220,214}},coins={{46,238},{120,238},{282,206},{330,206},{432,176},{480,176},{582,146},{630,146},{732,116},{780,116},{882,86},{930,86},{1032,58},{1080,58},{1182,58},{1230,58},{1332,58},{1380,58},{1510,58},{1570,58}},keys={},hazards={{"spike",210,248,50,12},{"spike",360,248,50,12},{"spike",510,248,50,12},{"spike",660,248,50,12},{"spike",810,248,50,12},{"spike",960,248,50,12},{"spike",1110,248,50,12},{"spike",1260,248,50,12},{"spike",1410,248,50,12}},springs={{220,244,28,16,260},{370,244,28,16,260},{520,244,28,16,260},{670,244,28,16,260}},movers={},enemies={{"ghost",1240,52,64},{"ghost",1520,40,64}},boxes={},checkpoints={{1010,58}},need_key=false,theme="tower",decor={{"bubble",1480,32},{"bubble",1540,26}}},
{name="Sign School",width=1720,spawn={18,220},goal={1672,220},solids={{0,260,160,36},{230,260,150,36},{450,260,140,36},{660,260,150,36},{880,260,150,36},{1100,260,150,36},{1320,260,150,36},{1540,260,180,36},{100,210,72,16},{300,190,72,16},{520,206,72,16},{720,190,72,16},{960,206,72,16},{1180,190,72,16},{1400,206,72,16}},coins={{42,238},{118,186},{190,238},{252,238},{320,166},{352,166},{470,238},{542,182},{606,238},{682,166},{742,166},{890,238},{962,182},{1026,238},{1120,238},{1200,166},{1236,166},{1340,238},{1418,182},{1488,238},{1622,238},{1672,238}},keys={{1220,158}},hazards={{"spike",160,248,70,12},{"spike",380,248,70,12},{"spike",590,248,70,12},{"spike",810,248,70,12},{"spike",1030,248,70,12},{"spike",1250,248,70,12},{"spike",1470,248,70,12}},springs={{414,244,28,16,250},{1070,244,28,16,250}},movers={},enemies={{"slug",760,240,60},{"slug",1450,240,60}},boxes={{1284,228,28,32}},checkpoints={{880,236}},need_key=true,theme="meadow",decor={{"sign",176,236},{"sign",592,236},{"sign",1034,236},{"sign",1468,236}}},
{name="Double Lift",width=1760,spawn={18,220},goal={1712,180},solids={{0,260,180,36},{250,260,130,36},{450,260,130,36},{650,260,130,36},{860,260,130,36},{1080,260,130,36},{1300,230,130,66},{1510,200,250,96},{120,208,72,16},{535,188,72,16},{970,188,72,16},{1360,176,72,16}},coins={{44,238},{126,184},{200,238},{272,238},{332,238},{466,238},{540,164},{610,238},{672,238},{876,238},{950,164},{1018,238},{1102,238},{1210,238},{1316,206},{1366,152},{1412,152},{1560,176},{1640,176}},keys={},hazards={{"spike",180,248,70,12},{"spike",380,248,70,12},{"spike",580,248,70,12},{"spike",780,248,80,12},{"spike",990,248,90,12},{"spike",1210,248,90,12}},springs={},movers={{192,220,50,12,"y",74,48},{396,220,50,12,"x",60,54},{598,220,50,12,"y",74,48},{810,220,50,12,"x",60,54},{1020,220,50,12,"y",74,48},{1232,220,50,12,"x",60,54}},enemies={{"ghost",1120,120,70},{"slug",1560,180,60}},boxes={},checkpoints={{1030,236}},need_key=false,theme="moving",decor={{"sign",208,236},{"sign",816,236},{"sign",1224,236}}},
{name="Picnic Return",width=1800,spawn={18,220},goal={1752,220},solids={{0,260,170,36},{230,260,170,36},{470,260,170,36},{710,260,170,36},{950,260,170,36},{1190,260,170,36},{1450,260,350,36},{100,205,70,16},{300,188,84,16},{520,196,84,16},{760,178,90,16},{1000,188,86,16},{1260,176,90,16},{1520,188,86,16}},coins={{40,238},{118,181},{190,238},{250,238},{324,164},{360,164},{492,238},{548,172},{590,172},{736,238},{786,154},{828,154},{972,238},{1028,164},{1070,164},{1220,238},{1286,152},{1324,152},{1472,238},{1544,164},{1586,164},{1680,238},{1740,238}},keys={{1298,144}},hazards={{"spike",170,248,60,12},{"spike",400,248,70,12},{"spike",640,248,70,12},{"spike",880,248,70,12},{"spike",1120,248,70,12},{"spike",1360,248,90,12}},springs={},movers={{188,220,48,12,"y",70,52},{438,212,48,12,"x",80,62},{678,208,48,12,"y",75,50},{918,220,48,12,"x",86,58},{1160,210,48,12,"y",80,48}},enemies={{"slug",344,240,60},{"ghost",614,132,70},{"slug",824,240,60},{"ghost",1110,116,60},{"slug",1600,240,60}},boxes={{1412,228,28,32}},checkpoints={{1360,236}},need_key=true,theme="meadow",decor={{"house",1660,228},{"sign",1390,236}}},
{name="Video Finale",width=1880,spawn={18,220},goal={1830,150},solids={{0,260,170,36},{240,260,120,36},{430,260,120,36},{620,260,120,36},{810,260,120,36},{1000,260,120,36},{1190,230,130,66},{1380,200,130,96},{1570,170,130,126},{1750,140,130,156},{110,210,72,16},{320,182,72,16},{510,154,72,16},{700,182,72,16},{890,154,72,16},{1080,182,72,16},{1270,154,72,16},{1460,126,72,16},{1650,98,72,16}},coins={{42,238},{120,186},{190,238},{258,238},{338,158},{352,158},{448,238},{528,130},{542,130},{638,238},{718,158},{732,158},{828,238},{908,130},{922,130},{1018,238},{1098,158},{1112,158},{1208,206},{1288,130},{1302,130},{1400,176},{1478,102},{1492,102},{1590,146},{1668,74},{1682,74},{1790,122}},keys={{1292,122}},hazards={{"spike",170,248,70,12},{"spike",360,248,70,12},{"spike",550,248,70,12},{"spike",740,248,70,12},{"spike",930,248,70,12},{"spike",1120,248,70,12},{"spike",1320,248,60,12},{"spike",1510,248,60,12}},springs={{186,244,28,16,255},{376,244,28,16,255},{566,244,28,16,255},{756,244,28,16,255},{946,244,28,16,255}},movers={{1140,220,54,12,"y",70,50},{1340,220,54,12,"x",70,55},{1540,220,54,12,"y",78,50}},enemies={{"ghost",600,118,70},{"slug",1160,210,58},{"ghost",1530,96,70},{"slug",1730,150,58}},boxes={{1320,228,28,32}},checkpoints={{980,236},{1540,236}},need_key=true,theme="cloud",decor={{"bubble",1460,68},{"bubble",1510,58},{"bubble",1560,48},{"sign",1318,236},{"house",1808,108}}}
}
for i=1,#StageData.stages do
local s=StageData.stages[i]
s.oneways=s.oneways or {}
s.switches=s.switches or {}
s.gates=s.gates or {}
s.crumbles=s.crumbles or {}
end
StageData.stages[2].oneways={{148,224,48,8},{370,218,54,8}}
StageData.stages[4].oneways={{172,204,54,8},{468,188,56,8}}
StageData.stages[7].oneways={{154,222,48,8},{350,200,54,8},{728,200,58,8}}
StageData.stages[9].oneways={{160,224,50,8},{342,210,52,8},{676,188,56,8}}
StageData.stages[12].oneways={{202,220,48,8},{520,196,52,8},{842,170,56,8}}
StageData.stages[16].oneways={{182,224,50,8},{600,198,54,8},{1008,176,58,8}}
StageData.stages[19].oneways={{220,220,52,8},{760,188,56,8},{1170,160,58,8}}
StageData.stages[22].oneways={{198,224,48,8},{660,194,54,8},{1110,166,56,8}}
StageData.stages[25].oneways={{420,212,52,8},{980,184,56,8},{1470,158,58,8}}
StageData.stages[26].oneways={{300,218,50,8},{860,190,54,8},{1430,142,58,8}}
StageData.stages[5].switches={{314,242,1}}
StageData.stages[5].gates={{520,204,18,56,1}}
StageData.stages[8].switches={{520,172,1}}
StageData.stages[8].gates={{874,204,18,56,1}}
StageData.stages[13].switches={{1012,172,1}}
StageData.stages[13].gates={{1208,174,18,56,1}}
StageData.stages[18].switches={{806,122,1}}
StageData.stages[18].gates={{1124,174,18,56,1}}
StageData.stages[23].switches={{1198,172,1}}
StageData.stages[23].gates={{1450,204,18,56,1}}
StageData.stages[26].switches={{1260,136,1}}
StageData.stages[26].gates={{1716,104,18,60,1}}
StageData.stages[6].crumbles={{236,214,48,10,0.55,2.2},{470,202,48,10,0.55,2.2}}
StageData.stages[10].crumbles={{280,216,50,10,0.50,2.0},{650,188,52,10,0.50,2.0}}
StageData.stages[14].crumbles={{360,208,48,10,0.48,2.0},{820,178,52,10,0.48,2.0}}
StageData.stages[17].crumbles={{520,204,50,10,0.45,1.9},{1080,176,52,10,0.45,1.9}}
StageData.stages[21].crumbles={{390,212,50,10,0.42,1.8},{910,184,52,10,0.42,1.8}}
StageData.stages[24].crumbles={{680,194,52,10,0.40,1.8},{1280,164,54,10,0.40,1.8}}
StageData.stages[26].crumbles={{1050,184,52,10,0.38,1.7},{1530,128,54,10,0.38,1.7}}
for i=1,#StageData.stages do
local s=StageData.stages[i]
s.npcs=s.npcs or {}
s.boss=s.boss or nil
s.secret=s.secret or nil
end
StageData.stages[1].npcs={{62,228,"MIMI","Welcome to Green Hills!","Coins improve your rank.","Press 5 near me to talk."}}
StageData.stages[4].npcs={{105,176,"PIP","Springs launch you high.","Release jump for short hops.","Watch the landing spot!"}}
StageData.stages[7].npcs={{790,214,"MIMI","A giant guardian is ahead.","Stomp its head three times.","The exit opens after victory."}}
StageData.stages[8].npcs={{96,194,"TIKO","Moving Skies begins here.","Ride platforms carefully.","Some switches open gates."}}
StageData.stages[10].npcs={{520,224,"PIP","Crusher Hall has a secret.","Look for a glowing portal.","Press DOWN to enter it."}}
StageData.stages[13].npcs={{1070,220,"TIKO","Picnic Guardian blocks exit.","Watch the charge pattern.","Stomp only when it lands."}}
StageData.stages[14].npcs={{92,220,"LUMA","Ghost Garden hides paths.","One-way ledges help climbing.","Secrets shine on the map."}}
StageData.stages[17].npcs={{520,226,"LUMA","This canyon has a hidden room.","Search near the high ledge.","DOWN enters secret portals."}}
StageData.stages[19].npcs={{1330,214,"LUMA","The Phantom Keeper awaits.","It dives after hovering.","Bounce on it when vulnerable."}}
StageData.stages[20].npcs={{100,194,"MIMI","Final world: Cat Tower.","Crumble blocks do not wait.","Keep moving upward!"}}
StageData.stages[24].npcs={{1170,218,"PIP","A last secret is nearby.","Its gem marks the world map.","Find all four gems!"}}
StageData.stages[26].npcs={{1540,150,"MIMI","The Sky Warden is here.","Learn all its patterns.","Finish the journey!"}}
StageData.stages[7].boss={"moss","MOSS KING",850,214,760,954,3}
StageData.stages[13].boss={"charge","PICNIC BRUTE",1110,236,1000,1250,4}
StageData.stages[19].boss={"phantom","PHANTOM KEEPER",1420,128,1320,1580,4}
StageData.stages[26].boss={"warden","SKY WARDEN",1660,120,1540,1840,5}
local function add_secret(stage_i,entry_x,entry_y,name)
local s=StageData.stages[stage_i]
local oldw=s.width
local room=oldw+70
s.width=oldw+340
s.secret={entry_x,entry_y,room+20,220,room+235,220,entry_x-24,entry_y,room+138,174,name}
table.insert(s.solids,{room,260,270,36})
table.insert(s.solids,{room+48,214,72,14})
table.insert(s.solids,{room+145,188,72,14})
table.insert(s.solids,{room+205,232,45,12})
table.insert(s.coins,{room+72,190})
table.insert(s.coins,{room+172,164})
table.insert(s.coins,{room+225,208})
end
add_secret(3,454,180,"BOX ATTIC")
add_secret(10,575,206,"CRUSHER VAULT")
add_secret(17,1010,160,"CANYON DEN")
add_secret(24,1320,206,"LIFT LOFT")
Sprites = Sprites or {}
Sprites.atlas_enabled = false
Sprites.atlas = nil
Sprites.map = {
cat={0,0,16,16}, slug={16,0,16,12}, ghost={32,0,16,16}, coin={48,0,8,12},
key={56,0,12,8}, spring={68,0,16,8}, box={84,0,16,16}, door={100,0,16,24}
}
function Sprites.load()
Sprites.atlas = Engine.load_image("assets/sprite_atlas.png")
Sprites.atlas_enabled = Sprites.atlas ~= nil and Engine.has_images
end
function Sprites.draw(name,x,y)
if not Sprites.atlas_enabled then return false end
local r=Sprites.map[name]; if not r then return false end
if not Engine.image_region(Sprites.atlas,r[1],r[2],r[3],r[4],x,y) then Sprites.atlas_enabled=false; return false end
return true
end
Audio = Audio or {}
Audio.enabled=true; Audio.q={}; Audio.head=1; Audio.tail=1; Audio.count=0; Audio.cap=4; Audio.cool=0
for i=1,Audio.cap do Audio.q[i]={f=0,ms=0} end
function Audio.push(f,ms)
if not Audio.enabled or Audio.count>=Audio.cap then return end
local e=Audio.q[Audio.tail]; e.f=f; e.ms=ms; Audio.tail=Audio.tail%Audio.cap+1; Audio.count=Audio.count+1
end
function Audio.update(dt)
if not Audio.enabled then return end
if Audio.cool>0 then Audio.cool=Audio.cool-dt; return end
if Audio.count>0 then
local e=Audio.q[Audio.head]
if not Engine.play_tone(e.f,e.ms) then Audio.enabled=false; return end
Audio.head=Audio.head%Audio.cap+1; Audio.count=Audio.count-1; Audio.cool=(e.ms/1000)+0.02
end
end
function Audio.coin() Audio.push(880,45) end
function Audio.jump() Audio.push(520,35) end
function Audio.hurt() Audio.push(180,90) end
function Audio.spring() Audio.push(740,70) end
function Audio.clear() Audio.push(1040,120) end
Save = Save or {}
Save.path="catbox.sav"
Save.data={unlocked=1,best_coins=0,sound=1,debug=0,last_level=1}
Save.stars={}
Save.secrets={}
for i=1,26 do
Save.stars[i]=0
Save.secrets[i]=0
end
local function parse(s)
if type(s)~="string" then return end
for line in string.gmatch(s,"[^\r\n]+") do
local k,v=string.match(line,"^([%w_]+)=([%-%d]+)$")
if k and v then
local n=tonumber(v)
local si=string.match(k,"^star_(%d+)$")
local hi=string.match(k,"^secret_(%d+)$")
if si then
si=tonumber(si)
if si and si>=1 and si<=26 then Save.stars[si]=math.max(0,math.min(3,n or 0)) end
elseif hi then
hi=tonumber(hi)
if hi and hi>=1 and hi<=26 then Save.secrets[hi]=(n and n~=0) and 1 or 0 end
elseif Save.data[k]~=nil then
Save.data[k]=n or Save.data[k]
end
end
end
end
function Save.load()
parse(Engine.file_read(Save.path))
Audio.enabled=Save.data.sound~=0
if Save.data.unlocked<1 then Save.data.unlocked=1 end
if Save.data.unlocked>26 then Save.data.unlocked=26 end
if Save.data.last_level<1 then Save.data.last_level=1 end
if Save.data.last_level>Save.data.unlocked then Save.data.last_level=Save.data.unlocked end
end
function Save.get_star(level)
return Save.stars[level] or 0
end
function Save.set_star(level,value)
if level<1 or level>26 then return end
value=math.max(0,math.min(3,value or 0))
if value>(Save.stars[level] or 0) then Save.stars[level]=value end
end
function Save.get_secret(level)
return Save.secrets[level] or 0
end
function Save.set_secret(level,value)
if level<1 or level>26 then return end
Save.secrets[level]=(value and value~=0) and 1 or 0
end
function Save.total_stars()
local n=0
for i=1,26 do n=n+(Save.stars[i] or 0) end
return n
end
function Save.total_secrets()
local n=0
for i=1,26 do n=n+(Save.secrets[i] or 0) end
return n
end
function Save.write()
local s="unlocked="..Save.data.unlocked..
"\nbest_coins="..Save.data.best_coins..
"\nsound="..(Audio.enabled and 1 or 0)..
"\ndebug="..Save.data.debug..
"\nlast_level="..Save.data.last_level.."\n"
for i=1,26 do
s=s.."star_"..i.."="..(Save.stars[i] or 0).."\n"
s=s.."secret_"..i.."="..(Save.secrets[i] or 0).."\n"
end
Engine.file_write(Save.path,s)
end
WorldMap = WorldMap or {}
WorldMap.worlds = {
{name="GREEN HILLS", first=1,  last=7,  theme="meadow", accent=0x5FC875, boss="MOSS KING", tagline="Sunny paths and soft grass."},
{name="MOVING SKIES",first=8, last=13, theme="moving", accent=0x72C6EA, boss="PICNIC BRUTE", tagline="Machines, lifts and shifting routes."},
{name="GHOST GARDEN",first=14,last=19, theme="ghost", accent=0xA78AD8, boss="PHANTOM KEEPER", tagline="Hidden ledges and haunted air."},
{name="CAT TOWER",first=20,last=26, theme="tower", accent=0xE3B95C, boss="SKY WARDEN", tagline="Climb above the clouds."},
}
WorldMap.node_xy = {
{26,210},{62,179},{99,208},{137,172},{176,205},{207,170},{146,238}
}
WorldMap.secret_levels = {3,10,17,24}
function WorldMap.world_for_level(level)
for i=1,#WorldMap.worlds do
local w=WorldMap.worlds[i]
if level>=w.first and level<=w.last then return i,w end
end
return 1,WorldMap.worlds[1]
end
function WorldMap.clamp_level(level, unlocked)
local max=math.max(1,math.min(unlocked or 1,#StageData.stages))
if level<1 then return max end
if level>max then return 1 end
return level
end
function WorldMap.next_unlocked(level, dir, unlocked)
local max=math.max(1,math.min(unlocked or 1,#StageData.stages))
local n=level+(dir or 1)
if n<1 then n=max end
if n>max then n=1 end
return n
end
function WorldMap.world_star_total(world_i)
local w=WorldMap.worlds[world_i]
if not w then return 0 end
local total=0
for i=w.first,w.last do total=total+(Save.get_star(i) or 0) end
return total
end
function WorldMap.world_secret_total(world_i)
local w=WorldMap.worlds[world_i]
if not w then return 0 end
local total=0
for i=w.first,w.last do total=total+(Save.get_secret(i) or 0) end
return total
end
function WorldMap.world_max_stars(world_i)
local w=WorldMap.worlds[world_i]
if not w then return 0 end
return (w.last-w.first+1)*3
end
function WorldMap.world_completion(world_i)
local max=WorldMap.world_max_stars(world_i)
if max<=0 then return 0 end
return math.floor((WorldMap.world_star_total(world_i)*100)/max)
end
function WorldMap.total_stars()
local total=0
for i=1,#StageData.stages do total=total+(Save.get_star(i) or 0) end
return total
end
function WorldMap.is_boss_level(level)
local s=StageData.stages[level]
return s and s.boss~=nil
end
function WorldMap.is_secret_level(level)
local s=StageData.stages[level]
return s and s.secret~=nil
end
DebugUI = DebugUI or {}
DebugUI.on=false; DebugUI.page=1; DebugUI.fps=0; DebugUI.acc=0; DebugUI.frames=0; DebugUI.peak=0; DebugUI.gc_step=0; DebugUI.gc_full=0
function DebugUI.update(dt)
DebugUI.acc=DebugUI.acc+dt; DebugUI.frames=DebugUI.frames+1
if DebugUI.acc>=1 then DebugUI.fps=DebugUI.frames/DebugUI.acc; DebugUI.acc=0; DebugUI.frames=0 end
local k=collectgarbage("count"); if k>DebugUI.peak then DebugUI.peak=k end
end
function DebugUI.gcstep()
collectgarbage("step",64); DebugUI.gc_step=DebugUI.gc_step+1
end
function DebugUI.fullgc() collectgarbage("collect"); DebugUI.gc_full=DebugUI.gc_full+1 end
function DebugUI.draw(g)
if not DebugUI.on then return end
Engine.rect(0,24,240,56,0x111111)
local heap=math.floor(collectgarbage("count")); local m,real=Engine.memory_info()
Engine.text(2,26,"DBG"..DebugUI.page.." #=OFF *=PAGE 9=GC",0xFFFFFF)
Engine.text(2,38,string.format("FPS %.1f LUA %dK PK %dK",DebugUI.fps,heap,math.floor(DebugUI.peak)),0xFFFFFF)
Engine.text(2,50,"OBJ E"..g.ecount.." FX"..g.fxcount.." C"..g.coins.." L"..g.lives,0xFFFFFF)
Engine.text(2,62,"GC S"..DebugUI.gc_step.." F"..DebugUI.gc_full.." ATL "..(Sprites.atlas_enabled and "ON" or "OFF"),0xFFFFFF)
end
Render = Render or {}
local floor=math.floor
local abs=math.abs
local sin=math.sin
local function sx(g,x) return floor(x-g.camera_x) end
local function px(x,y,w,h,c) if w>0 and h>0 then Engine.rect(x,y,w,h,c) end end
local THEMES = {
meadow={sky=0x82CFFF, far=0xA4E7AE, mid=0x82D98D, near=0x63C875, ground=0xF6B45B, top=0x56C864, sun=0xFFE48A, flower=0xFFF4A0},
moving={sky=0x86D0FE, far=0xA9E8B1, mid=0x8BDA92, near=0x66C97A, ground=0xF6B45B, top=0x56C864, sun=0xFFE58D, flower=0xDFF6FF},
ghost={sky=0x8CCAF4, far=0xAFDEB2, mid=0x89CF91, near=0x61B977, ground=0xF1B15A, top=0x59C767, sun=0xFFF0A8, flower=0xEEDFFF},
danger={sky=0x8ACAF9, far=0xA8E19F, mid=0x81D184, near=0x5FC06F, ground=0xF0B15A, top=0x59C766, sun=0xFFD97A, flower=0xFFD0A0},
bubble={sky=0x8FD5FF, far=0xB3ECB7, mid=0x91DEA0, near=0x70CD83, ground=0xF7B75E, top=0x5DCB72, sun=0xFFF3B7, flower=0xD8F8FF},
tower={sky=0x84CBFF, far=0xA6E2A6, mid=0x82D18B, near=0x62BF75, ground=0xF3B35C, top=0x59C868, sun=0xFFE28C, flower=0xFFF0A4},
cloud={sky=0x92D9FF, far=0xB7EDBD, mid=0x95E2A3, near=0x76D18A, ground=0xF7BA64, top=0x61CD79, sun=0xFFF1B0, flower=0xF5FCFF},
boxland={sky=0x8CCFFF, far=0xA8E5AB, mid=0x86D58C, near=0x64C277, ground=0xF3B45B, top=0x58C866, sun=0xFFE28C, flower=0xFFE7A0}
}
local function theme_for_name(name)
return THEMES[name] or THEMES.meadow
end
local function get_theme(g)
if g and g.st and g.st.theme then return theme_for_name(g.st.theme) end
return THEMES.meadow
end
local function draw_cloud(x,y,scale)
scale=scale or 1
local h=4*scale
px(x+4*scale,y+4*scale,22*scale,h,0xFFFFFF)
px(x+9*scale,y,12*scale,8*scale,0xFFFFFF)
px(x+18*scale,y+4*scale,12*scale,h,0xFFFFFF)
end
local function draw_hill(x,base,w,h,color)
local step=8
local rows=floor(h/step)
for i=0,rows do
local yy=base-i*step
local inset=floor((i/rows)*(w*0.44))
px(x+inset,yy,w-inset*2,step,color)
end
end
local function draw_bush(x,y,w,h,c1,c2)
c1=c1 or 0x51C86B
c2=c2 or 0x73E38B
px(x,y+6,w,h-6,c1)
px(x+3,y+2,w-6,10,c2)
px(x+5,y+8,2,2,0x2F8E46)
px(x+w-8,y+9,2,2,0x2F8E46)
end
local function draw_sun(x,y,c)
px(x+4,y,10,2,c)
px(x+2,y+2,14,10,c)
px(x+4,y+12,10,2,c)
end
local function draw_flower(x,y,c)
px(x+2,y+2,1,4,0x2E934A)
px(x,y,2,2,c)
px(x+3,y,2,2,c)
px(x+1,y+1,3,2,0xFFF7CC)
end
function Render.background(g)
local t=get_theme(g)
Engine.clear(t.sky)
draw_sun(190-floor(g.camera_x*0.015)%8,18,t.sun)
local p1=floor(g.camera_x*0.05)%120
local p2=floor(g.camera_x*0.11)%150
local p3=floor(g.camera_x*0.18)%170
draw_hill(-70-p1,242,180,112,t.far)
draw_hill(80-p1,242,190,128,t.far)
draw_hill(-100-p2,246,210,102,t.mid)
draw_hill(90-p2,246,220,118,t.mid)
draw_hill(-90-p3,250,210,90,t.near)
draw_hill(110-p3,250,220,100,t.near)
for i=0,4 do
draw_cloud(18+i*66-(floor(g.camera_x*0.07)%66),34+(i%2)*18,1)
end
px(0,240,240,80,0x9BE89F)
for i=0,7 do
local x=i*38-(floor(g.camera_x*0.22)%38)
draw_bush(x,228+(i%2)*2,20,12)
end
for i=0,8 do
local x=i*31-(floor(g.camera_x*0.28)%31)
draw_flower(x+5,250+(i%2)*6,t.flower)
end
end
local function platform_checker(x,y,w,h,fill,top)
px(x,y,w,h,fill)
px(x,y,w,4,top)
px(x,y+4,w,2,0xA9E77B)
local yy=y+7
local row=0
while yy<y+h do
local xx=x+((row%2==0) and 0 or 8)
while xx<x+w do
px(xx,yy,8,8,0xF8D77D)
xx=xx+16
end
row=row+1
yy=yy+8
end
end
function Render.platform(g,r,is_mover)
local t=get_theme(g)
local x=sx(g,r[1])
local y=r[2]+24
local w=r[3]
local h=r[4]
if x+w<0 or x>240 then return end
platform_checker(x,y,w,h,is_mover and 0xE7BF6A or t.ground,is_mover and 0x88E8A4 or t.top)
if is_mover then
px(x+4,y+h-4,w-8,2,0x8F6A48)
px(x+6,y+7,3,3,0xFFF0A3)
px(x+w-9,y+7,3,3,0xFFF0A3)
end
end
function Render.oneway(g,r)
local x=sx(g,r[1])
local y=r[2]+24
if x+r[3]<0 or x>240 then return end
px(x,y,r[3],r[4],0x75D889)
px(x,y,r[3],2,0xC3F2A9)
for i=4,r[3]-4,8 do px(x+i,y+r[4]-2,4,2,0x4DAF67) end
end
function Render.crumble(g,c)
if not c.active then return end
local x=sx(g,c.x)
local y=c.y+24
if x+c.w<0 or x>240 then return end
local blink=(c.timer>c.delay*0.65) and (floor(Engine.time_ms/80)%2==0)
local fill=blink and 0xFFD990 or 0xE7B96B
px(x,y,c.w,c.h,fill)
px(x,y,c.w,2,0x7ED88C)
for i=4,c.w-4,10 do
px(x+i,y+4,4,2,0xA97A45)
px(x+i+2,y+7,2,2,0x8D653E)
end
end
function Render.switch(g,s)
local x=sx(g,s[1])
local y=s[2]+24
local on=g.switch_on[s[3]]==true
px(x-2,y-4,14,8,0x6D6F79)
px(x,y-7,10,5,on and 0x64D889 or 0xF0A85A)
px(x+3,y-9,4,2,on and 0xB9F7C5 or 0xFFE4A0)
end
function Render.gate(g,d)
if g.switch_on[d[5]] then return end
local x=sx(g,d[1])
local y=d[2]+24
if x+d[3]<0 or x>240 then return end
px(x,y,d[3],d[4],0x596174)
px(x+3,y,d[3]-6,d[4],0x7F899E)
local yy=y+4
while yy<y+d[4] do
px(x+2,yy,d[3]-4,2,0xB2BDCC)
yy=yy+9
end
end
function Render.coin(g,x,y)
local t=Engine.time_ms*0.012+x*0.1
local bob=sin(t)*1.5
local phase=floor(t)%4
local w=(phase==0 and 2) or (phase==1 and 4) or 6
x=sx(g,x)
y=y+24+bob
if x<-10 or x>250 then return end
px(x-floor(w/2),y-5,w,10,0xFFD85A)
if w>=4 then px(x-1,y-3,2,6,0xFFF2A6) end
end
function Render.key(g,x,y)
local t=Engine.time_ms*0.010+x*0.12
local bob=sin(t)*1.0
x=sx(g,x)
y=y+24+bob
if x<-14 or x>250 then return end
px(x-6,y-2,9,4,0xF6D04D)
px(x+2,y-4,5,8,0xF6D04D)
if floor(Engine.time_ms/180)%4==0 then
px(x+7,y-8,2,2,0xFFF6C5)
px(x+10,y-5,1,1,0xFFFFFF)
end
end
local function draw_cat_proc(p,x,y)
local pose=p.pose or "idle"
local dir=p.dir or 1
local blink=floor(Engine.time_ms/220)%10==0
local body_y=y+6
local body_h=8
local leg_y=y+13
local leg1_x=x+4
local leg2_x=x+10
local tail_x=(dir>0) and (x+1) or (x+13)
px(x+4,y+15,9,1,0x4A7659) -- tiny shadow
if pose=="run1" then
body_y=y+7
leg1_x=x+3
leg2_x=x+11
elseif pose=="run2" then
body_y=y+6
leg_y=y+14
leg1_x=x+5
leg2_x=x+9
elseif pose=="jump" then
body_y=y+5
leg_y=y+11
leg1_x=x+5
leg2_x=x+9
tail_x=(dir>0) and x or (x+14)
elseif pose=="fall" then
body_y=y+7
body_h=7
leg_y=y+14
end
px(tail_x,y+7,2,5,0x1A2230)
px(x+2,body_y,12,body_h,0x1A2230)
px(x+3,y+1,10,7,0x1A2230)
px(x+3,y,3,3,0x1A2230)
px(x+10,y,3,3,0x1A2230)
px(leg1_x,leg_y,2,3,0x111824)
px(leg2_x,leg_y,2,3,0x111824)
px(x+6,y+7,4,3,0xEAEFF5)
if not blink then
if dir>0 then
px(x+7,y+4,1,2,0xF5F5F5)
px(x+11,y+4,1,2,0xF5F5F5)
else
px(x+4,y+4,1,2,0xF5F5F5)
px(x+8,y+4,1,2,0xF5F5F5)
end
end
px(x+7,y+8,2,1,0xF19AB3)
end
function Render.cat(g)
local p=g.p
if p.inv>0 and floor(Engine.time_ms/90)%2==0 then return end
draw_cat_proc(p,sx(g,p.x),p.y+24)
end
function Render.enemy(g,e)
local x=sx(g,e.x)
local y=e.y+24
if e.kind=="ghost" then
local bob=floor(sin(e.t*4)*1.5)
y=y+bob
px(x+2,y+2,12,10,0xF7F7F7)
px(x+4,y+12,2,2,0xF7F7F7)
px(x+8,y+12,2,2,0xF7F7F7)
px(x+12,y+12,2,2,0xF7F7F7)
px(x+4,y+6,2,3,0x333333)
px(x+10,y+6,2,3,0x333333)
px(x+6,y+10,4,1,0xFFCAD6)
else
local lift=(floor(e.t*10)%2==0) and 0 or 1
y=y+4+lift
px(x+1,y+7,14,7,0xD75E4D)
px(x+9,y+3,5,5,0xE87362)
if e.dir>=0 then px(x+11,y+5,1,2,0x333333) else px(x+4,y+5,1,2,0x333333) end
px(x+4,y+13,2,1,0x7E2F24)
px(x+10,y+13,2,1,0x7E2F24)
end
end
function Render.box(g,b)
local x=sx(g,b.x)
local y=b.y+24
px(x,y,b.w,b.h,0xC98D55)
px(x+3,y+3,b.w-6,b.h-6,0xE8B87C)
px(x+11,y+11,6,2,0xA56D3C)
px(x+3,y+3,2,b.h-6,0xB67843)
px(x+b.w-5,y+3,2,b.h-6,0xB67843)
end
function Render.hazard(g,h)
local x=sx(g,h[2])
local y=h[3]+24
if x+h[4]<-16 or x>256 then return end
if h[1]=="spike" then
local n=floor(h[4]/8)
for i=0,n-1 do
px(x+i*8,y+8,2,4,0x6A7180)
px(x+i*8+2,y+5,2,7,0x838BA0)
px(x+i*8+4,y+2,2,10,0xA4AFC2)
end
else
local pulse=(floor(Engine.time_ms/180)%2==0) and 0x5D6576 or 0x70798C
px(x+12,y-18,6,18,0x444D63)
px(x,y,h[4],h[5],pulse)
px(x+6,y+h[5]-12,h[4]-12,12,0x505766)
end
end
function Render.spring(g,s)
local x=sx(g,s[1])
local y=s[2]+24
local pulse=floor(Engine.time_ms/120)%2
px(x,y,s[3],s[4],0x4CC67B)
px(x+3,y+2+(pulse==1 and 1 or 0),s[3]-6,3,0x9BF0B0)
px(x+2,y+7,s[3]-4,2,0x2C8C51)
end
function Render.goal(g)
local x=sx(g,g.goal[1])
local y=g.goal[2]+24
px(x,y,18,40,0xB77A4C)
px(x+3,y+4,12,32,0xE8B67F)
px(x+12,y+21,2,2,0x3D2E2A)
if (g.st.need_key and not g.has_key) or (g.boss and not g.boss.dead) then
px(x+6,y+14,6,8,(g.boss and not g.boss.dead) and 0x7B8492 or 0xD6A847)
else
if floor(Engine.time_ms/220)%3==0 then px(x+5,y+8,2,2,0xFFF3B8) end
end
end
function Render.decor(g,d)
local kind=d[1]
local x=sx(g,d[2])
local y=(d[3] or 0)+24
if kind=="sign" then
px(x+4,y-18,2,18,0x7C5C38)
px(x,y-18,28,14,0xF7D57D)
px(x+2,y-16,24,10,0xD97C49)
Engine.text(x+5,y-15,"!",0xFFFFFF)
elseif kind=="house" then
px(x,y-14,20,14,0xF7F7F7)
px(x+3,y-10,14,10,0xC8D7F4)
px(x+6,y-6,4,6,0xB77A4C)
px(x+3,y-20,14,6,0xC84B4B)
elseif kind=="bubble" then
local b=floor(Engine.time_ms/200)%3
px(x,y-b,10,2,0xD4F4FF)
px(x,y+8-b,10,2,0xD4F4FF)
px(x,y+2-b,2,6,0xD4F4FF)
px(x+8,y+2-b,2,6,0xD4F4FF)
elseif kind=="fence" then
for i=0,4 do px(x+i*6,y-10,2,10,0xF4F4F4) end
px(x,y-8,26,2,0xF4F4F4)
px(x,y-4,26,2,0xF4F4F4)
elseif kind=="pipe" then
px(x,y-10,16,10,0x53C973)
px(x-2,y-14,20,6,0x79E48B)
elseif kind=="bush" then
draw_bush(x,y-10,18,12)
end
end
function Render.checkpoint(g,c,i)
local x=sx(g,c[1])
local y=c[2]+24
local active=(g.active_checkpoint==i)
local wave=floor(Engine.time_ms/180)%2
px(x+2,y-16,2,16,0x7C5C38)
px(x+4,y-16,10+wave*2,6,active and 0xFFD96E or 0xD0E4F8)
if active then px(x+6,y-10,2,2,0xFFF5C8) end
end
function Render.fx(g)
for i=1,#g.fx do
local f=g.fx[i]
if f.active then
local x=sx(g,f.x)
local y=f.y+24
if x>-8 and x<248 and y>-8 and y<328 then
px(x,y,f.w,f.h,f.color)
if f.kind=="spark" then px(x+1,y+1,1,1,0xFFF8D0) end
end
end
end
end
local function draw_star(x,y,on)
local c=on and 0xFFD85A or 0xC8BFA7
px(x+3,y,3,2,c)
px(x+1,y+2,7,3,c)
px(x+2,y+5,5,2,c)
px(x+1,y+7,2,2,c)
px(x+6,y+7,2,2,c)
end
local function softbar(left,right)
px(0,302,240,18,0xEED9A8)
Engine.text(4,305,left or "",0x3A3428)
if right then Engine.text(168,305,right,0x3A3428) end
end
function Render.ui(g)
px(0,0,240,24,0xF8E4B7)
Engine.text(4,4,"LEVEL "..g.level_i,0x222222)
for i=1,3 do
local x=58+(i-1)*10
local c=(i<=g.lives) and 0xB9D1F4 or 0xB8C5D7
px(x,7,6,6,c)
px(x+1,13,4,2,c)
end
if g.has_key then
Render.key(g,g.camera_x+96,-10)
else
px(90,8,12,8,0xD8C68D)
end
Render.coin(g,g.camera_x+184,-8)
Engine.text(194,4,tostring(g.level_coins).."/"..tostring(#g.st.coins),0x222222)
end
local function draw_lock(x,y)
px(x+3,y,6,5,0x66707A)
px(x+1,y+4,10,8,0x89939E)
px(x+5,y+7,2,3,0x394149)
end
local function draw_secret_badge(x,y,found)
local c=found and 0x9FEAFF or 0x9FA8AD
px(x+3,y,3,2,c)
px(x+1,y+2,7,4,c)
px(x+3,y+6,3,2,c)
if found then px(x+4,y+2,1,1,0xFFFFFF) end
end
local function draw_crown(x,y,on)
local c=on and 0xFFD75A or 0x9EA4A7
px(x,y+3,12,4,c)
px(x+1,y,2,4,c)
px(x+5,y+1,2,3,c)
px(x+9,y,2,4,c)
end
local function draw_world_progress(x,y,w,pct,accent)
px(x,y,w,6,0xD7CBAA)
local fw=floor((w*pct)/100)
if fw>0 then px(x,y,fw,6,accent) end
px(x,y,w,1,0xFFF5D8)
end
local function map_player_marker(x,y)
local bob=floor(sin(Engine.time_ms*0.01)*2)
px(x+2,y-14+bob,10,7,0x1A2230)
px(x+2,y-16+bob,3,3,0x1A2230)
px(x+9,y-16+bob,3,3,0x1A2230)
px(x+5,y-11+bob,1,1,0xFFFFFF)
px(x+9,y-11+bob,1,1,0xFFFFFF)
px(x+6,y-8+bob,2,1,0xF19AB3)
end
local function draw_worldmap(g)
local wi,w=WorldMap.world_for_level(g.map_level)
local t=theme_for_name(w.theme)
Engine.clear(t.sky)
draw_sun(194,18,t.sun)
draw_cloud(16,38,1)
draw_cloud(150,54,1)
draw_hill(-80,262,190,112,t.far)
draw_hill(80,262,205,126,t.mid)
px(0,244,240,58,0x98E5A0)
for i=0,6 do
draw_bush(i*42-(floor(Engine.time_ms/500)%8),235+(i%2)*3,18,11)
end
px(0,0,240,42,0xF7E7BC)
px(0,40,240,2,w.accent)
Engine.text(8,6,"WORLD "..wi.." / "..#WorldMap.worlds,0x39414A)
Engine.text(8,21,w.name,0x222222)
Engine.text(176,7,WorldMap.world_star_total(wi).."/"..WorldMap.world_max_stars(wi),0x5A513D)
draw_star(210,5,true)
Engine.text(176,22,WorldMap.world_completion(wi).."%",0x5A513D)
px(10,48,220,72,0xFFF3D1)
px(12,50,4,68,w.accent)
Engine.text(22,56,w.tagline,0x4E5358)
Engine.text(22,74,"Boss: "..w.boss,0x5D5545)
Engine.text(22,92,"Secrets: "..WorldMap.world_secret_total(wi),0x5D5545)
Engine.text(126,92,"Up/Down: world",0x6A685E)
draw_world_progress(22,108,190,WorldMap.world_completion(wi),w.accent)
local count=w.last-w.first+1
local node_y_shift=-10
for local_i=1,count do
local level=w.first+local_i-1
local pos=WorldMap.node_xy[local_i]
local x=pos[1]
local y=pos[2]+node_y_shift
if local_i<count then
local np=WorldMap.node_xy[local_i+1]
local x2=np[1]
local y2=np[2]+node_y_shift
local minx=math.min(x,x2)
local miny=math.min(y,y2)
local ww=math.max(4,abs(x2-x))
local hh=math.max(3,abs(y2-y))
if abs(x2-x)>abs(y2-y) then
px(minx+8,floor((y+y2)/2),math.max(3,ww-10),3,0xD5BE80)
else
px(floor((x+x2)/2),miny+8,3,math.max(3,hh-8),0xD5BE80)
end
end
local unlocked=level<=Save.data.unlocked
local selected=(level==g.map_level)
local boss=WorldMap.is_boss_level(level)
local secret=WorldMap.is_secret_level(level)
local node_w=boss and 22 or 18
local node_h=boss and 20 or 18
local nx=x-floor(node_w/2)+4
local ny=y-floor(node_h/2)+4
if selected then
px(nx-5,ny-5,node_w+10,node_h+10,0xF2CB58)
px(nx-3,ny-3,node_w+6,node_h+6,0xFFF7D7)
map_player_marker(nx+2,ny)
end
if unlocked then
px(nx,ny,node_w,node_h,boss and 0xFFE29A or 0xFFF1C6)
px(nx+2,ny+2,node_w-4,node_h-4,boss and 0xE7B05A or 0xE9D9AE)
if boss then
draw_crown(nx+5,ny-7,Save.get_star(level)>0)
else
Engine.text(nx+4,ny+2,tostring(level),0x2B2B2B)
end
else
px(nx,ny,node_w,node_h,0xA9B4B0)
draw_lock(nx+3,ny+3)
end
local stars=Save.get_star(level)
for s=1,3 do
draw_star(nx-2+(s-1)*7,ny+node_h+2,s<=stars)
end
if secret then
draw_secret_badge(nx+node_w-1,ny-8,Save.get_secret(level)==1)
end
end
local st=StageData.stages[g.map_level]
px(10,250,220,48,0xFFF2CB)
Engine.text(18,255,"LEVEL "..g.map_level.."  "..st.name,0x222222)
if st.boss then
Engine.text(18,273,"BOSS STAGE",0xA65A3A)
elseif st.secret then
Engine.text(18,273,(Save.get_secret(g.map_level)==1) and "SECRET FOUND" or "SECRET HIDDEN",0x4B7480)
else
Engine.text(18,273,"Best: "..Save.get_star(g.map_level).." star(s)",0x555555)
end
if g.map_level==Save.data.unlocked then Engine.text(170,273,"NEW",0xC46A3A) end
softbar("4/6 MOVE  5 PLAY","RSK BACK")
end
local NPC_COLORS={
MIMI=0xE8B07B,
PIP=0xB7D5F1,
TIKO=0xE7CE72,
LUMA=0xC9B0E8
}
function Render.npc(g,n)
local x=sx(g,n[1])
local y=n[2]+24-16
if x<-20 or x>250 then return end
local c=NPC_COLORS[n[3]] or 0xE6C18C
px(x+3,y+6,10,9,c)
px(x+4,y+2,8,7,c)
px(x+4,y,3,4,c)
px(x+9,y,3,4,c)
px(x+6,y+5,1,2,0x2A3036)
px(x+10,y+5,1,2,0x2A3036)
px(x+7,y+8,2,1,0xF5D2C3)
px(x+4,y+15,2,2,0x735B48)
px(x+10,y+15,2,2,0x735B48)
local p=g.p
if abs((p.x+p.w*0.5)-n[1])<28 and abs((p.y+p.h)-n[2])<32 and not g.dialog.active then
px(x-5,y-15,27,12,0xFFF8DA)
Engine.text(x+2,y-13,"5 TALK",0x514C42)
end
end
function Render.dialog(g)
if not g.dialog.active then return end
local n=g.st.npcs[g.dialog.npc]
if not n then return end
local line=n[g.dialog.line+3] or "..."
px(8,226,224,72,0x2B3038)
px(10,228,220,68,0xFFF1CF)
px(16,234,54,16,NPC_COLORS[n[3]] or 0xE6C18C)
Engine.text(21,237,n[3],0x2A2A2A)
Engine.text(16,257,line,0x3A3A3A)
Engine.text(16,278,"5 NEXT",0x6B6254)
Engine.text(166,278,"RSK CLOSE",0x6B6254)
end
local function draw_portal(g,x,y,active)
x=sx(g,x)
y=y+24-27
local pulse=floor(Engine.time_ms/110)%3
local c=active and 0x9FE8FF or 0xBDDDE8
px(x+3,y,12,2,c)
px(x+1,y+2,16,20,c)
px(x+3,y+4,12,16,0x577E92)
px(x+5,y+5,8,14,(pulse==0) and 0xC8F6FF or 0x91DBF4)
px(x+7,y+8,4,8,0xE9FCFF)
end
function Render.secret(g)
local s=g.st.secret
if not s then return end
if g.secret_inside then
draw_portal(g,s[5],s[6],true)
if Save.get_secret(g.level_i)==0 then
local x=sx(g,s[9])
local y=s[10]+24+floor(sin(Engine.time_ms*0.012)*2)
px(x+3,y,4,2,0xBDF6FF)
px(x+1,y+2,8,6,0x76D8F2)
px(x+3,y+8,4,2,0xBDF6FF)
px(x+4,y+2,1,2,0xFFFFFF)
end
else
draw_portal(g,s[1],s[2],true)
local x=sx(g,s[1])
local y=s[2]+24-39
if x>-20 and x<250 then
px(x-1,y,24,10,0xFFF6D7)
Engine.text(x+4,y+1,"8 ENTER",0x4F5960)
end
end
end
local function boss_body_moss(x,y,b)
px(x+2,y+7,24,15,0x65B95D)
px(x+6,y+2,16,11,0x81D575)
px(x+7,y,4,4,0x81D575)
px(x+18,y,4,4,0x81D575)
px(x+9,y+6,2,3,0x24342B)
px(x+18,y+6,2,3,0x24342B)
draw_crown(x+8,y-6,b.hp>0)
end
local function boss_body_charge(x,y)
px(x+2,y+6,24,16,0xC4724E)
px(x+5,y+3,18,8,0xE29465)
px(x,y+10,5,5,0x7D4937)
px(x+23,y+10,5,5,0x7D4937)
px(x+8,y+7,2,2,0x222222)
px(x+18,y+7,2,2,0x222222)
px(x+6,y+21,5,3,0x5A4034)
px(x+17,y+21,5,3,0x5A4034)
end
local function boss_body_phantom(x,y)
px(x+3,y+2,22,16,0xF2EDF8)
px(x+5,y+16,4,5,0xF2EDF8)
px(x+12,y+16,4,5,0xF2EDF8)
px(x+20,y+16,4,5,0xF2EDF8)
px(x+7,y+7,3,4,0x433A50)
px(x+18,y+7,3,4,0x433A50)
px(x+11,y+13,7,2,0xC49BCD)
end
local function boss_body_warden(x,y,b)
px(x+4,y+4,20,17,0x47556F)
px(x+7,y,14,8,0x617494)
px(x+2,y+8,4,8,0xBDDFF5)
px(x+24,y+8,4,8,0xBDDFF5)
px(x+8,y+7,3,3,0xF7D967)
px(x+18,y+7,3,3,0xF7D967)
px(x+11,y+14,7,2,0x202633)
if floor(Engine.time_ms/120)%2==0 then
px(x-2,y+12,3,3,0xE7F9FF)
px(x+28,y+12,3,3,0xE7F9FF)
end
end
local function skill_icon(k,x,y,warn)
px(x,y,16,16,warn and 0xF2C75C or 0xD4C49D);px(x+1,y+1,14,14,0xFFF5D8)
if k==1 then px(x+5,y+3,2,9,0x65B95D);px(x+9,y+3,2,9,0x65B95D)
elseif k==2 then px(x+3,y+6,4,4,0xC4724E);px(x+9,y+6,4,4,0xC4724E);px(x+7,y+4,2,8,0x7D4937)
elseif k==3 then px(x+4,y+4,8,8,0xC49BCD);px(x+6,y+6,4,4,0xF2EDF8)
else px(x+8,y+3,2,3,0x8DDCF8);px(x+6,y+6,3,2,0x8DDCF8);px(x+8,y+8,2,3,0x8DDCF8);px(x+5,y+11,3,2,0x8DDCF8) end
end
function Render.bs(g)
for i=1,#g.bs do local s=g.bs[i]; if s.active then local x=sx(g,s.x);local y=s.y+24
if s.k==1 then px(x,y,s.w,s.h,0x65B95D);px(x+3,y-2,3,2,0xA6E59D)
elseif s.k==2 then px(x,y,s.w,s.h,0xE29465);px(x+2,y-2,s.w-4,2,0xFFD4A8)
elseif s.k==3 then px(x,y,s.w,s.h,0xC49BCD);px(x+2,y+2,s.w-4,s.h-4,0xF2EDF8)
elseif s.s==0 then if floor(Engine.time_ms/80)%2==0 then px(x+5,y,2,s.h,0xF7D967) end
else px(x+3,y,6,s.h,0x8DDCF8);px(x+5,y,2,s.h,0xFFFFFF) end
end end
end
local function boss_cut(g,b)
if not b or (b.cut or 0)<=0 then return end
local shake=(floor(Engine.time_ms/55)%2==0) and 2 or -2
px(22+shake,82,196,78,0x20252E);px(26+shake,86,188,70,0xFFF3D1)
px(30+shake,90,4,62,0xF0B85A);px(198+shake,90,4,62,0xF0B85A)
local w=(b.word==2 and "BOOM!") or (b.word==3 and "WHOO!") or (b.word==4 and "ZAP!") or "ROAR!"
px(66+shake,101,108,30,0xFFF8E8);Engine.text(81+shake,109,w,0x6A4436)
px(44+shake,139,30,2,0xD56555);px(52+shake,135,2,10,0xD56555);px(166+shake,139,28,2,0xD56555);px(183+shake,134,2,11,0xD56555)
px(34+shake,94,14,2,0xF2C75C);px(38+shake,96,14,2,0xF2C75C);px(186+shake,94,14,2,0xF2C75C)
end
function Render.boss(g)
local b=g.boss
if not b or b.dead then return end
local x=sx(g,b.x)
local y=b.y+24
if x>-40 and x<260 then
if b.kind=="moss" then boss_body_moss(x,y,b)
elseif b.kind=="charge" then boss_body_charge(x,y)
elseif b.kind=="phantom" then boss_body_phantom(x,y)
else boss_body_warden(x,y,b) end
if b.inv>0 and floor(Engine.time_ms/70)%2==0 then
px(x-2,y-2,b.w+4,b.h+4,0xFFF2B5)
end
end
if b.engaged then
px(20,27,200,25,0x303640);px(22,29,196,21,0xFFF0CC)
Engine.text(28,31,b.name,0x3A3330)
local hpw=60;px(108,34,hpw,7,0xC7B79C);local fill=floor(hpw*(b.hp/b.max_hp));if fill>0 then px(108,34,fill,7,0xD56555) end
skill_icon(b.skill or 1,178,31,b.warn==1)
if b.warn==1 then Engine.text(198,31,"!",0xB94F45) end
local barrier_x=sx(g,b.arena_l-10)
if barrier_x>-12 and barrier_x<245 then
local yy=60
while yy<260 do
px(barrier_x,yy,8,8,0x8DD9F2)
px(barrier_x+2,yy+2,4,4,0xD9F7FF)
yy=yy+12
end
end
end
end
function Render.secret_banner(g)
if g.secret_banner<=0 or not g.st.secret then return end
px(42,86,156,46,0x26323B)
px(44,88,152,42,0xE9F8FF)
Engine.text(70,96,"SECRET AREA",0x365466)
Engine.text(58,114,g.st.secret[11],0x4E6370)
end
function Render.draw(g)
if g.state=="splash" then
Render.background(g)
px(30,82,180,132,0xFFF1C8)
Engine.text(57,101,"CAT IN A LITTLE BOX",0x222222)
Engine.text(76,124,"WORLD JOURNEY",0x6A5434)
draw_cat_proc({pose=(floor(Engine.time_ms/240)%2==0) and "run1" or "run2",dir=1},110,151)
Engine.text(70,184,"NOKIA 225 / MRE",0x555555)
return
end
if g.state=="menu" then
Render.background(g)
px(28,48,184,238,0xFFF1C8)
Engine.text(55,66,"CAT IN A LITTLE BOX",0x222222)
draw_cat_proc({pose=(floor(Engine.time_ms/260)%2==0) and "run1" or "run2",dir=1},42,78)
local items={"CONTINUE","WORLD MAP","SETTINGS","ABOUT","EXIT"}
for i=1,#items do
local y=106+(i-1)*31
if i==g.menu_index then px(48,y-4,144,22,0xF6D67A) end
Engine.text(70,y,items[i],0x222222)
end
Engine.text(48,264,"Stars: "..Save.total_stars().."/78",0x555555)
return
end
if g.state=="worldmap" then
draw_worldmap(g)
return
end
if g.state=="settings" then
Render.background(g)
px(28,70,184,176,0xFFF1C8)
Engine.text(84,88,"SETTINGS",0x222222)
Engine.text(60,126,"SOUND: "..(Audio.enabled and "ON" or "OFF"),0x222222)
Engine.text(46,152,"DEBUG: #  *  9 keys",0x555555)
Engine.text(51,178,"5 toggle sound",0x555555)
softbar("5 TOGGLE","RSK BACK")
return
end
if g.state=="about" then
Render.background(g)
px(18,50,204,226,0xFFF1C8)
Engine.text(92,67,"ABOUT",0x222222)
Engine.text(28,97,"Cat platform adventure",0x333333)
Engine.text(28,116,"26 stages / 4 worlds",0x333333)
Engine.text(28,135,"One-way + crumble + gates",0x333333)
Engine.text(28,154,"Stars + world progression",0x333333)
Engine.text(28,173,"240x320 / 15 FPS",0x333333)
Engine.text(28,192,"Nokia 225 RM-1011",0x333333)
Engine.text(28,211,"VXPstore / Qeafivels",0x333333)
softbar("","RSK BACK")
return
end
Render.background(g)
local st=g.st
if st.decor then
for i=1,#st.decor do Render.decor(g,st.decor[i]) end
end
for i=1,#st.solids do Render.platform(g,st.solids[i],false) end
for i=1,#st.oneways do Render.oneway(g,st.oneways[i]) end
for i=1,#g.crumbles do Render.crumble(g,g.crumbles[i]) end
for i=1,#st.movers do
local m=g.movers[i]
if m then Render.platform(g,{m.x,m.y,m.w,m.h},true) end
end
for i=1,#st.gates do Render.gate(g,st.gates[i]) end
for i=1,#st.switches do Render.switch(g,st.switches[i]) end
for i=1,#st.hazards do Render.hazard(g,st.hazards[i]) end
for i=1,#st.springs do Render.spring(g,st.springs[i]) end
for i=1,#st.checkpoints do Render.checkpoint(g,st.checkpoints[i],i) end
for i=1,#g.boxes do if g.boxes[i].active then Render.box(g,g.boxes[i]) end end
for i=1,#st.coins do if g.coin_alive[i] then Render.coin(g,st.coins[i][1],st.coins[i][2]) end end
for i=1,#st.keys do if g.key_alive[i] then Render.key(g,st.keys[i][1],st.keys[i][2]) end end
for i=1,#g.enemies do
local e=g.enemies[i]
if e.active then Render.enemy(g,e) end
end
for i=1,#st.npcs do Render.npc(g,st.npcs[i]) end
Render.secret(g)
Render.boss(g)
Render.bs(g)
Render.fx(g)
Render.goal(g)
Render.cat(g)
Render.ui(g)
DebugUI.draw(g)
Render.secret_banner(g)
Render.dialog(g)
boss_cut(g,g.boss)
if g.intro_t>0 and g.state=="play" and not g.dialog.active then
local wi,w=WorldMap.world_for_level(g.level_i)
px(32,90,176,54,0xFFF1C8)
Engine.text(50,100,"WORLD "..wi.." - LEVEL "..g.level_i,0x222222)
Engine.text(46,121,g.st.name,0x555555)
end
if g.state=="pause" then
px(38,118,164,82,0x222222)
Engine.text(88,134,"PAUSED",0xFFFFFF)
Engine.text(58,154,"5 resume  0 restart",0xFFFFFF)
Engine.text(62,174,"RSK world map",0xFFFFFF)
end
if g.state=="clear" then
px(28,104,184,112,0xFFF1C8)
Engine.text(70,118,"LEVEL CLEAR!",0x222222)
for i=1,3 do draw_star(90+(i-1)*20,140,i<=g.earned_stars) end
Engine.text(58,165,"Coins: "..g.level_coins.."/"..#g.st.coins,0x333333)
Engine.text(58,182,"Hits:  "..g.level_hits,0x333333)
Engine.text(44,200,"5 MAP   0 REPLAY",0x222222)
end
if g.state=="gameover" then
px(42,124,156,70,0x222222)
Engine.text(78,140,"TRY AGAIN",0xFFFFFF)
Engine.text(57,159,"5 restart level",0xFFFFFF)
Engine.text(62,176,"RSK world map",0xFFFFFF)
end
end
Game = Game or {}
local G=Game
local abs=math.abs
local sin=math.sin
local cos=math.cos
local floor=math.floor
G.state="splash"
G.level_i=1
G.map_level=1
G.camera_x=0
G.coins=0
G.level_coins=0
G.level_hits=0
G.lives=3
G.has_key=false
G.gc_timer=0
G.splash_t=0
G.menu_index=1
G.input_lock=0
G.active_checkpoint=0
G.level_clear_timer=0
G.earned_stars=0
G.intro_t=0
G.secret_inside=false
G.secret_banner=0
G.dialog={active=false,npc=0,line=1}
G.boss=nil
G.enemies={}
G.boxes={}
G.fx={}
G.bs={}
G.movers={}
G.crumbles={}
G.coin_alive={}
G.key_alive={}
G.switch_on={}
G.ecount=0
G.fxcount=0
for i=1,6 do
G.enemies[i]={active=false,kind="slug",x=0,y=0,w=16,h=16,vx=0,vy=0,origin=0,range=0,t=0,dir=1,base_y=0}
end
for i=1,4 do
G.boxes[i]={active=false,x=0,y=0,w=28,h=32,vx=0,vy=0}
end
for i=1,12 do
G.fx[i]={active=false,kind="spark",t=0,max=0.3,x=0,y=0,vx=0,vy=0,color=0xFFFFFF,w=2,h=2}
end
for i=1,4 do G.bs[i]={active=false,k=0,t=0,x=0,y=0,vx=0,vy=0,w=8,h=8,s=0} end
G.p={
x=20,y=220,w=16,h=16,vx=0,vy=0,on_ground=false,coyote=0,jump_buf=0,inv=0,
checkpoint_x=20,checkpoint_y=220,dir=1,pose="idle",anim_t=0,step_t=0,
standing_mover=nil,step_emit=0,checkpoint_id=0
}
local prev={
jump=false,pause=false,dbg=false,page=false,gc=false,restart=false,
menu_up=false,menu_down=false,confirm=false,back=false,left=false,right=false,
map_up=false,map_down=false,talk=false,secret=false
}
local function hit(ax,ay,aw,ah,bx,by,bw,bh)
return ax<bx+bw and ax+aw>bx and ay<by+bh and ay+ah>by
end
local function pressed(name,now)
local v=now and not prev[name]
prev[name]=now
return v
end
local function fx_spawn(kind,x,y,vx,vy,color,life,w,h)
for i=1,#G.fx do
local f=G.fx[i]
if not f.active then
f.active=true
f.kind=kind or "spark"
f.x=x or 0
f.y=y or 0
f.vx=vx or 0
f.vy=vy or 0
f.color=color or 0xFFFFFF
f.t=0
f.max=life or 0.35
f.w=w or 2
f.h=h or 2
return f
end
end
return nil
end
local function fx_burst(x,y,count,color,speed,life)
count=count or 4
speed=speed or 34
life=life or 0.30
for i=1,count do
local a=(i/count)*6.28318
fx_spawn("spark",x,y,cos(a)*speed,(sin(a)*speed)-12,color,life,2,2)
end
end
local function gate_open(id)
return G.switch_on[id]==true
end
local function solid_iter(cb)
local st=G.st
for i=1,#st.solids do
local r=st.solids[i]
cb(r[1],r[2],r[3],r[4],nil)
end
for i=1,#G.movers do
local m=G.movers[i]
cb(m.x,m.y,m.w,m.h,m)
end
for i=1,#G.crumbles do
local c=G.crumbles[i]
if c.active then cb(c.x,c.y,c.w,c.h,c) end
end
for i=1,#st.gates do
local d=st.gates[i]
if not gate_open(d[5]) then cb(d[1],d[2],d[3],d[4],nil) end
end
if G.boss and G.boss.engaged and not G.boss.dead then
cb(G.boss.arena_l-10,24,10,236,nil)
end
end
local function reset_runtime_level(i)
if i<1 then i=1 end
if i>#StageData.stages then i=#StageData.stages end
G.level_i=i
G.map_level=i
G.st=StageData.stages[i]
G.goal=G.st.goal
G.camera_x=0
G.has_key=false
G.state="play"
G.input_lock=0.18
G.level_clear_timer=0
G.active_checkpoint=0
G.level_coins=0
G.level_hits=0
G.earned_stars=0
G.intro_t=0.85
G.switch_on={}
G.secret_inside=false
G.secret_banner=0
G.dialog.active=false
G.dialog.npc=0
G.dialog.line=1
G.boss=nil
if G.st.boss then
local b=G.st.boss
G.boss={
kind=b[1],name=b[2],x=b[3],y=b[4],base_x=b[3],base_y=b[4],
arena_l=b[5],arena_r=b[6],hp=b[7],max_hp=b[7],
w=28,h=24,vx=0,vy=0,t=0,attack_t=0,attack=0,phase=1,
dir=-1,engaged=false,dead=false,inv=0,sp=2.4,warn=0,skill=1,cut=0,word=0
}
end
local p=G.p
p.x=G.st.spawn[1]
p.y=G.st.spawn[2]
p.vx=0
p.vy=0
p.inv=0
p.on_ground=false
p.coyote=0
p.jump_buf=0
p.checkpoint_x=p.x
p.checkpoint_y=p.y
p.dir=1
p.pose="idle"
p.anim_t=0
p.step_t=0
p.step_emit=0
p.standing_mover=nil
p.checkpoint_id=0
G.coin_alive={}
for n=1,#G.st.coins do G.coin_alive[n]=true end
G.key_alive={}
for n=1,#G.st.keys do G.key_alive[n]=true end
for n=1,#G.enemies do G.enemies[n].active=false end
for n=1,#G.st.enemies do
local d=G.st.enemies[n]
local e=G.enemies[n]
e.active=true
e.kind=d[1]
e.x=d[2]
e.y=d[3]
e.base_y=d[3]
e.origin=d[2]
e.range=d[4]
e.vx=(d[1]=="slug") and 26 or 0
e.vy=0
e.t=n*0.7
e.dir=1
end
for n=1,#G.boxes do G.boxes[n].active=false end
for n=1,#G.st.boxes do
local d=G.st.boxes[n]
local b=G.boxes[n]
b.active=true
b.x=d[1]
b.y=d[2]
b.w=d[3]
b.h=d[4]
b.vx=0
b.vy=0
end
G.movers={}
for n=1,#G.st.movers do
local d=G.st.movers[n]
G.movers[n]={
x=d[1],y=d[2],w=d[3],h=d[4],axis=d[5],range=d[6],speed=d[7],
ox=d[1],oy=d[2],phase=n*0.9,dx=0,dy=0,active=true,carry=true
}
end
G.crumbles={}
for n=1,#G.st.crumbles do
local d=G.st.crumbles[n]
G.crumbles[n]={
x=d[1],y=d[2],w=d[3],h=d[4],delay=d[5] or 0.5,respawn=d[6] or 2.0,
timer=0,respawn_t=0,active=true,touch=false,crumble=true
}
end
for n=1,#G.fx do G.fx[n].active=false end
for n=1,#G.bs do G.bs[n].active=false end
Save.data.last_level=i
Save.write()
collectgarbage("collect")
end
function G.load_level(i)
reset_runtime_level(i)
end
function G.open_world_map(level)
G.map_level=WorldMap.clamp_level(level or Save.data.last_level,Save.data.unlocked)
G.state="worldmap"
G.camera_x=0
end
local function update_movers(dt)
local t=Engine.time_ms/1000
for i=1,#G.movers do
local m=G.movers[i]
local px0,py0=m.x,m.y
local off=sin((t+m.phase)*m.speed/60)*m.range
if m.axis=="x" then m.x=m.ox+off else m.y=m.oy+off end
m.dx=m.x-px0
m.dy=m.y-py0
end
end
local function update_crumbles(dt)
for i=1,#G.crumbles do
local c=G.crumbles[i]
if c.active then
if c.touch then
c.timer=c.timer+dt
if c.timer>=c.delay then
c.active=false
c.respawn_t=c.respawn
c.timer=0
fx_burst(c.x+c.w*0.5,c.y+2,5,0xE9C27A,32,0.28)
Audio.push(240,45)
end
elseif c.timer>0 then
c.timer=math.max(0,c.timer-dt*0.35)
end
else
c.respawn_t=c.respawn_t-dt
if c.respawn_t<=0 then
c.active=true
c.timer=0
fx_burst(c.x+c.w*0.5,c.y+2,4,0xD8F0A0,24,0.22)
end
end
c.touch=false
end
end
local function apply_mover_carry()
local p=G.p
local m=p.standing_mover
if m and m.active and m.carry then
p.x=p.x+m.dx
p.y=p.y+m.dy
end
end
local function update_player_pose(dt,moving)
local p=G.p
p.anim_t=p.anim_t+dt
if not p.on_ground then
p.pose=(p.vy<0) and "jump" or "fall"
p.step_emit=0
return
end
if moving then
p.step_t=p.step_t+dt*(1.5+abs(p.vx)/45)
p.step_emit=p.step_emit+dt*abs(p.vx)
if p.step_t>=0.36 then p.step_t=p.step_t-0.36 end
if p.step_emit>40 then
p.step_emit=0
fx_spawn("dust",p.x+((p.dir>0) and 3 or 11),p.y+p.h-2,-p.dir*8,-6,0xD9F1BE,0.20,3,2)
end
if p.step_t<0.18 then p.pose="run1" else p.pose="run2" end
else
p.step_t=0
p.step_emit=0
p.pose="idle"
end
end
local function resolve_oneways(oldy,ny)
local p=G.p
if p.vy<0 then return ny,nil end
local stand=nil
for i=1,#G.st.oneways do
local r=G.st.oneways[i]
local y=r[2]
if oldy+p.h<=y+3 and hit(p.x,ny,p.w,p.h,r[1],y,r[3],r[4]) then
ny=y-p.h
p.vy=0
p.on_ground=true
stand=r
break
end
end
return ny,stand
end
local function move_player(dt)
local p=G.p
apply_mover_carry()
local left=Engine.down("LEFT","4")
local right=Engine.down("RIGHT","6")
local jump=Engine.down("UP","5")
if left and not right then
p.vx=p.vx-420*dt
p.dir=-1
elseif right and not left then
p.vx=p.vx+420*dt
p.dir=1
else
p.vx=p.vx*(1-math.min(1,9*dt))
end
if p.vx>92 then p.vx=92 elseif p.vx<-92 then p.vx=-92 end
if G.input_lock<=0 and pressed("jump",jump) then p.jump_buf=0.12 end
p.jump_buf=math.max(0,p.jump_buf-dt)
p.coyote=math.max(0,p.coyote-dt)
if p.jump_buf>0 and (p.on_ground or p.coyote>0) then
p.vy=-178
p.on_ground=false
p.coyote=0
p.jump_buf=0
p.standing_mover=nil
Audio.jump()
fx_spawn("dust",p.x+5,p.y+p.h-1,-10,-20,0xF4F4F4,0.18,3,2)
fx_spawn("dust",p.x+10,p.y+p.h-1,10,-20,0xF4F4F4,0.18,3,2)
elseif not jump and p.vy<-80 then
p.vy=p.vy+460*dt
end
p.vy=p.vy+430*dt
if p.vy>210 then p.vy=210 end
local nx=p.x+p.vx*dt
solid_iter(function(x,y,w,h)
if hit(nx,p.y,p.w,p.h,x,y,w,h) then
if p.vx>0 then nx=x-p.w elseif p.vx<0 then nx=x+w end
p.vx=0
end
end)
for i=1,#G.boxes do
local b=G.boxes[i]
if b.active and hit(nx,p.y,p.w,p.h,b.x,b.y,b.w,b.h) then
local dir=(p.vx>=0) and 1 or -1
local bx=b.x+dir*38*dt
local blocked=false
solid_iter(function(x,y,w,h)
if hit(bx,b.y,b.w,b.h,x,y,w,h) then blocked=true end
end)
if not blocked then
b.x=bx
nx=p.x+p.vx*dt
fx_spawn("dust",b.x+b.w*0.5,b.y+b.h-2,dir*5,-4,0xD5BB84,0.16,3,2)
else
nx=p.x
p.vx=0
end
end
end
p.x=nx
local oldy=p.y
local ny=p.y+p.vy*dt
local was_ground=p.on_ground
local landed_mover=nil
p.on_ground=false
solid_iter(function(x,y,w,h,obj)
if hit(p.x,ny,p.w,p.h,x,y,w,h) then
if p.vy>0 and oldy+p.h<=y+4 then
ny=y-p.h
if not was_ground and p.vy>70 then
fx_spawn("dust",p.x+4,ny+p.h-2,-8,-8,0xE8F4D2,0.18,3,2)
fx_spawn("dust",p.x+11,ny+p.h-2,8,-8,0xE8F4D2,0.18,3,2)
end
p.vy=0
p.on_ground=true
if obj and obj.carry then landed_mover=obj end
if obj and obj.crumble then obj.touch=true end
elseif p.vy<0 and oldy>=y+h-4 then
ny=y+h
p.vy=0
end
end
end)
if not p.on_ground then
local oy
ny,oy=resolve_oneways(oldy,ny)
end
if was_ground and not p.on_ground then p.coyote=0.10 end
p.y=ny
p.standing_mover=landed_mover
update_player_pose(dt,(left and not right) or (right and not left))
end
local function hurt()
local p=G.p
if p.inv>0 then return end
G.level_hits=G.level_hits+1
G.lives=G.lives-1
Audio.hurt()
p.inv=1.2
fx_burst(p.x+8,p.y+8,6,0xFFB0A0,44,0.34)
if G.lives<=0 then
G.state="gameover"
G.lives=3
else
p.x=p.checkpoint_x
p.y=p.checkpoint_y
p.vx=0
p.vy=0
p.standing_mover=nil
end
end
local function bs_spawn(k,x,y,vx,vy,w,h,life)
for i=1,#G.bs do local s=G.bs[i]; if not s.active then s.active=true;s.k=k;s.t=life;s.x=x;s.y=y;s.vx=vx;s.vy=vy;s.w=w;s.h=h;s.s=0;return end end
end
local function update_bs(dt)
local p=G.p
for i=1,#G.bs do local s=G.bs[i]; if s.active then
s.t=s.t-dt; if s.t<=0 then s.active=false else
if s.k<4 then s.x=s.x+s.vx*dt;s.y=s.y+s.vy*dt elseif s.s==0 and s.t<0.28 then s.s=1;fx_burst(s.x+4,110,5,0xEAFBFF,38,0.2) end
if (s.k~=4 or s.s==1) and hit(p.x,p.y,p.w,p.h,s.x,s.y,s.w,s.h) then hurt(); if s.k<4 then s.active=false end end
end
end end
end
local function boss_special(b,p,p2)
local cx=b.x+14; b.cut=0.65;b.warn=0
if b.kind=="moss" then b.skill=1;b.word=1;bs_spawn(1,cx,b.base_y+18,(p.x<cx) and -105 or 105,0,14,7,1.0);Audio.push(420,55)
elseif b.kind=="charge" then b.skill=2;b.word=2;bs_spawn(2,cx,b.base_y+20,(p.x<cx) and -145 or 145,0,18,6,0.9);Audio.push(180,65)
elseif b.kind=="phantom" then b.skill=3;b.word=3;local dx=p.x-cx;local dy=p.y-b.y;local m=math.max(1,abs(dx)+abs(dy));bs_spawn(3,cx,b.y+8,dx/m*90,dy/m*90,10,10,2.0);Audio.push(560,45)
else b.skill=4;b.word=4;local x=math.max(b.arena_l+8,math.min(b.arena_r-8,p.x));bs_spawn(4,x,40,0,0,12,220,0.72);Audio.push(760,45) end
fx_burst(cx,b.y+10,p2 and 7 or 5,(b.kind=="phantom") and 0xDCCBFF or ((b.kind=="warden") and 0xBDEFFF or 0xFFD0A0),42,0.28)
end
local function update_boxes(dt)
for i=1,#G.boxes do
local b=G.boxes[i]
if b.active then
b.vy=b.vy+360*dt
if b.vy>180 then b.vy=180 end
local ny=b.y+b.vy*dt
solid_iter(function(x,y,w,h)
if hit(b.x,ny,b.w,b.h,x,y,w,h) and b.y+b.h<=y+5 and b.vy>=0 then
ny=y-b.h
b.vy=0
end
end)
b.y=ny
end
end
end
local function update_enemies(dt)
G.ecount=0
for i=1,#G.enemies do
local e=G.enemies[i]
if e.active then
G.ecount=G.ecount+1
e.t=e.t+dt
if e.kind=="slug" then
e.x=e.x+e.vx*dt
if e.x<e.origin-e.range then e.x=e.origin-e.range; e.vx=abs(e.vx) end
if e.x>e.origin+e.range then e.x=e.origin+e.range; e.vx=-abs(e.vx) end
e.dir=(e.vx>=0) and 1 or -1
else
e.x=e.origin+sin(e.t*1.4)*e.range
e.y=e.base_y+sin(e.t*2.1)*6
end
local p=G.p
if hit(p.x,p.y,p.w,p.h,e.x,e.y,e.w,e.h) then
if p.vy>45 and p.y+p.h<e.y+9 then
e.active=false
p.vy=-125
Audio.push(330,55)
G.coins=G.coins+2
fx_burst(e.x+8,e.y+8,5,0xFFF0B0,40,0.28)
else
hurt()
end
end
end
end
end
local function update_fx(dt)
G.fxcount=0
for i=1,#G.fx do
local f=G.fx[i]
if f.active then
G.fxcount=G.fxcount+1
f.t=f.t+dt
if f.t>=f.max then
f.active=false
else
if f.kind=="dust" then
f.vy=f.vy+14*dt
f.vx=f.vx*0.94
else
f.vy=f.vy+56*dt
end
f.x=f.x+f.vx*dt
f.y=f.y+f.vy*dt
end
end
end
end
local function boss_is_clear()
return (not G.boss) or G.boss.dead
end
local function boss_defeat()
local b=G.boss
if not b or b.dead then return end
b.dead=true
b.engaged=false
b.hp=0
b.vx=0
b.vy=0
Audio.push(1040,150)
fx_burst(b.x+b.w*0.5,b.y+b.h*0.5,12,0xFFF0A0,60,0.50)
end
local function boss_take_hit()
local b=G.boss
if not b or b.dead or b.inv>0 then return end
b.hp=b.hp-1
b.inv=0.55
G.p.vy=-138
Audio.push(360,70)
fx_burst(b.x+b.w*0.5,b.y+5,7,0xFFF2B0,44,0.32)
if b.hp<=0 then boss_defeat() end
end
local function update_boss(dt)
local b=G.boss
if not b or b.dead then return end
b.t=b.t+dt
b.attack_t=b.attack_t+dt
b.inv=math.max(0,b.inv-dt)
local p=G.p
if not b.engaged then
if p.x>b.arena_l-36 then
b.engaged=true
b.attack_t=0
Audio.push(220,110)
b.cut=0.8;b.word=1
fx_burst(b.x+14,b.y+12,8,0xFFE2A0,40,0.35)
else
return
end
end
local left=b.arena_l+18
local right=b.arena_r-b.w-8
b.cut=math.max(0,(b.cut or 0)-dt);b.sp=(b.sp or 2.4)-dt;b.warn=(b.sp<0.65) and 1 or 0
if b.sp<=0 then boss_special(b,p,b.phase==2);b.sp=(b.phase==2) and 2.4 or 3.6 end
if b.kind=="moss" then
if b.attack_t>((b.hp<=1) and 1.35 or 2.2) and b.vy==0 then
b.attack_t=0
b.dir=(p.x>b.x) and 1 or -1
b.vx=b.dir*54
b.vy=-132
end
b.vy=b.vy+360*dt
b.x=b.x+b.vx*dt
b.y=b.y+b.vy*dt
if b.y>=b.base_y then b.y=b.base_y; b.vy=0; b.vx=b.dir*26 end
if b.x<left then b.x=left; b.dir=1; b.vx=abs(b.vx) end
if b.x>right then b.x=right; b.dir=-1; b.vx=-abs(b.vx) end
elseif b.kind=="charge" then
if b.attack==1 then
b.x=b.x+b.vx*dt
if b.attack_t>0.72 or b.x<=left or b.x>=right then
b.attack=0
b.attack_t=0
b.vx=0
end
else
if b.attack_t>((b.hp<=2) and 1.05 or 1.8) then
b.attack=1
b.attack_t=0
b.dir=(p.x>b.x) and 1 or -1
b.vx=b.dir*110
Audio.push(170,55)
else
b.x=b.x+sin(b.t*2.1)*7*dt
end
end
if b.x<left then b.x=left end
if b.x>right then b.x=right end
elseif b.kind=="phantom" then
if b.attack==1 then
b.y=b.y+120*dt
b.x=b.x+b.dir*42*dt
if b.y>=218 then
b.y=218
b.attack=2
b.attack_t=0
Audio.push(260,55)
end
elseif b.attack==2 then
b.y=b.y-92*dt
if b.y<=b.base_y then
b.y=b.base_y
b.attack=0
b.attack_t=0
end
else
b.x=(b.arena_l+b.arena_r-b.w)*0.5+sin(b.t*1.25)*62
b.y=b.base_y+sin(b.t*2.2)*18
if b.attack_t>((b.hp<=2) and 1.15 or 2.0) then
b.attack=1
b.attack_t=0
b.dir=(p.x>b.x) and 1 or -1
end
end
else -- warden
if b.attack==1 then
b.x=b.x+b.vx*dt
b.y=b.y+b.vy*dt
if b.attack_t>0.55 then
b.attack=0
b.attack_t=0
b.vx=0
b.vy=0
end
else
b.x=(b.arena_l+b.arena_r-b.w)*0.5+sin(b.t*1.35)*82
b.y=b.base_y+sin(b.t*2.0)*34
if b.attack_t>((b.hp<=2) and 0.95 or 1.55) then
b.attack=1
b.attack_t=0
local dx=p.x-b.x
local dy=p.y-b.y
local mag=math.max(1,abs(dx)+abs(dy))
b.vx=dx/mag*160
b.vy=dy/mag*160
Audio.push(300,45)
end
end
end
if hit(p.x,p.y,p.w,p.h,b.x,b.y,b.w,b.h) then
if p.vy>38 and p.y+p.h<b.y+10 and b.inv<=0 then
boss_take_hit()
elseif b.inv<=0 then
hurt()
end
end
end
local function npc_near_index()
if not G.st or not G.st.npcs then return 0 end
local p=G.p
for i=1,#G.st.npcs do
local n=G.st.npcs[i]
if abs((p.x+p.w*0.5)-n[1])<28 and abs((p.y+p.h)-n[2])<32 then return i end
end
return 0
end
local function handle_dialog(back)
local confirm=Engine.down("5","ENTER")
if G.dialog.active then
prev.jump=confirm
if pressed("talk",confirm) then
local n=G.st.npcs[G.dialog.npc]
G.dialog.line=G.dialog.line+1
if not n or G.dialog.line>5 or n[G.dialog.line+3]==nil then
G.dialog.active=false
G.dialog.npc=0
G.dialog.line=1
else
Audio.push(680,18)
end
elseif pressed("back",back) then
G.dialog.active=false
G.dialog.npc=0
G.dialog.line=1
end
return true
end
local ni=npc_near_index()
if ni>0 and pressed("talk",confirm) then
prev.jump=confirm
G.dialog.active=true
G.dialog.npc=ni
G.dialog.line=1
Audio.push(700,25)
return true
end
return false
end
local function handle_secret()
local s=G.st.secret
if not s then return false end
local p=G.p
local down=Engine.down("DOWN","8")
local near_entry=hit(p.x,p.y,p.w,p.h,s[1]-8,s[2]-28,28,34)
local near_exit=hit(p.x,p.y,p.w,p.h,s[5]-8,s[6]-28,28,34)
if pressed("secret",down) then
if (not G.secret_inside) and near_entry then
G.secret_inside=true
G.secret_banner=1.25
p.x=s[3]
p.y=s[4]
p.vx=0
p.vy=0
p.standing_mover=nil
G.camera_x=math.max(0,p.x-84)
Audio.push(820,70)
fx_burst(p.x+8,p.y+8,8,0xBEEFFF,42,0.35)
return true
elseif G.secret_inside and near_exit then
G.secret_inside=false
p.x=s[7]
p.y=s[8]
p.vx=0
p.vy=0
p.standing_mover=nil
G.camera_x=math.max(0,p.x-84)
Audio.push(620,70)
fx_burst(p.x+8,p.y+8,6,0xD8F6FF,36,0.28)
return true
end
end
if G.secret_inside and Save.get_secret(G.level_i)==0 then
if hit(p.x,p.y,p.w,p.h,s[9]-6,s[10]-8,14,16) then
Save.set_secret(G.level_i,1)
Save.write()
G.coins=G.coins+5
Audio.push(1180,120)
fx_burst(s[9],s[10],10,0xA8F4FF,52,0.44)
end
end
return false
end
local function activate_switches()
local p=G.p
for i=1,#G.st.switches do
local s=G.st.switches[i]
local id=s[3]
if not G.switch_on[id] and hit(p.x,p.y,p.w,p.h,s[1]-4,s[2]-8,18,16) then
G.switch_on[id]=true
Audio.push(760,80)
fx_burst(s[1]+5,s[2]-3,7,0xA8F0FF,42,0.32)
end
end
end
local function compute_level_stars()
local total=#G.st.coins
local stars=1
if total==0 or G.level_coins*100>=total*70 then stars=2 end
if (total==0 or G.level_coins>=total) and G.level_hits==0 then stars=3 end
return stars
end
local function triggers()
local p=G.p
local st=G.st
activate_switches()
for i=1,#st.coins do
if G.coin_alive[i] then
local c=st.coins[i]
if hit(p.x,p.y,p.w,p.h,c[1]-4,c[2]-6,8,12) then
G.coin_alive[i]=false
G.coins=G.coins+1
G.level_coins=G.level_coins+1
Audio.coin()
fx_burst(c[1],c[2],4,0xFFE07A,32,0.22)
end
end
end
for i=1,#st.keys do
if G.key_alive[i] then
local c=st.keys[i]
if hit(p.x,p.y,p.w,p.h,c[1]-6,c[2]-4,12,8) then
G.key_alive[i]=false
G.has_key=true
Audio.push(980,70)
fx_burst(c[1],c[2],5,0xFFF2A6,40,0.26)
end
end
end
for i=1,#st.springs do
local s=st.springs[i]
if p.vy>=0 and hit(p.x,p.y,p.w,p.h,s[1],s[2],s[3],s[4]) then
p.vy=-s[5]
p.y=s[2]-p.h
p.on_ground=false
p.standing_mover=nil
Audio.spring()
fx_burst(s[1]+s[3]*0.5,s[2],5,0xB5F4C2,40,0.24)
end
end
for i=1,#st.hazards do
local h=st.hazards[i]
if hit(p.x,p.y,p.w,p.h,h[2],h[3],h[4],h[5]) then hurt() end
end
for i=1,#st.checkpoints do
local c=st.checkpoints[i]
if abs(p.x-c[1])<18 then
p.checkpoint_x=c[1]
p.checkpoint_y=c[2]
p.checkpoint_id=i
if G.active_checkpoint~=i then
G.active_checkpoint=i
Audio.push(690,45)
fx_burst(c[1]+4,c[2]-10,5,0xFFF2A6,30,0.26)
end
end
end
if p.y>330 then hurt() end
if hit(p.x,p.y,p.w,p.h,G.goal[1],G.goal[2],22,44) and (not st.need_key or G.has_key) and boss_is_clear() then
G.state="clear"
G.level_clear_timer=0
G.earned_stars=compute_level_stars()
Audio.clear()
fx_burst(G.goal[1]+8,G.goal[2]+10,8,0xFFF2A6,48,0.40)
if G.level_i>=Save.data.unlocked then
Save.data.unlocked=math.min(#StageData.stages,G.level_i+1)
end
Save.set_star(G.level_i,G.earned_stars)
Save.data.last_level=math.min(Save.data.unlocked,G.level_i+1)
if G.coins>Save.data.best_coins then Save.data.best_coins=G.coins end
Save.write()
end
end
local function handle_worldmap(back)
local left=Engine.down("LEFT","4")
local right=Engine.down("RIGHT","6")
local up=Engine.down("UP","2")
local down=Engine.down("DOWN","8")
if pressed("left",left) then
G.map_level=WorldMap.next_unlocked(G.map_level,-1,Save.data.unlocked)
Audio.push(620,20)
end
if pressed("right",right) then
G.map_level=WorldMap.next_unlocked(G.map_level,1,Save.data.unlocked)
Audio.push(620,20)
end
if pressed("map_up",up) then
local wi=WorldMap.world_for_level(G.map_level)
wi=wi-1
if wi<1 then wi=#WorldMap.worlds end
local w=WorldMap.worlds[wi]
if w.first<=Save.data.unlocked then G.map_level=w.first end
end
if pressed("map_down",down) then
local wi=WorldMap.world_for_level(G.map_level)
wi=wi+1
if wi>#WorldMap.worlds then wi=1 end
local w=WorldMap.worlds[wi]
if w.first<=Save.data.unlocked then G.map_level=w.first end
end
if pressed("confirm",Engine.down("5","ENTER")) then
if G.map_level<=Save.data.unlocked then G.load_level(G.map_level) end
elseif pressed("back",back) then
G.state="menu"
end
end
function G.update(dt)
if dt>0.10 then dt=0.10 end
Engine.time_ms=Engine.time_ms+dt*1000
DebugUI.update(dt)
Audio.update(dt)
update_fx(dt)
if G.input_lock>0 then G.input_lock=math.max(0,G.input_lock-dt) end
if G.intro_t>0 then G.intro_t=math.max(0,G.intro_t-dt) end
if G.secret_banner>0 then G.secret_banner=math.max(0,G.secret_banner-dt) end
local back=Engine.down("SOFTRIGHT","BACK")
if G.state=="splash" then
G.splash_t=G.splash_t+dt
if G.splash_t>=1.2 or pressed("confirm",Engine.down("5","ENTER")) then G.state="menu" end
return
end
if G.state=="menu" then
local up=Engine.down("UP","2")
local down=Engine.down("DOWN","8")
if pressed("menu_up",up) then
G.menu_index=G.menu_index-1
if G.menu_index<1 then G.menu_index=5 end
Audio.push(620,25)
end
if pressed("menu_down",down) then
G.menu_index=G.menu_index+1
if G.menu_index>5 then G.menu_index=1 end
Audio.push(620,25)
end
if pressed("confirm",Engine.down("5","ENTER")) then
if G.menu_index==1 or G.menu_index==2 then
G.open_world_map(Save.data.last_level)
elseif G.menu_index==3 then
G.state="settings"
elseif G.menu_index==4 then
G.state="about"
else
Engine.exit()
end
end
return
end
if G.state=="worldmap" then
handle_worldmap(back)
return
end
if G.state=="settings" then
if pressed("confirm",Engine.down("5","ENTER")) then
Audio.enabled=not Audio.enabled
Save.data.sound=Audio.enabled and 1 or 0
Save.write()
end
if pressed("back",back) then G.state="menu" end
return
end
if G.state=="about" then
if pressed("back",back) or pressed("confirm",Engine.down("5","ENTER")) then G.state="menu" end
return
end
if G.state=="play" then
if handle_dialog(back) then return end
if handle_secret() then return end
end
local pa=Engine.down("SOFTLEFT","P")
if pressed("pause",pa) then
G.state=(G.state=="pause") and "play" or ((G.state=="play") and "pause" or G.state)
end
local db=Engine.down("#")
if pressed("dbg",db) then DebugUI.on=not DebugUI.on end
local pg=Engine.down("*")
if pressed("page",pg) then DebugUI.page=DebugUI.page%2+1 end
local gc=Engine.down("9")
if pressed("gc",gc) then DebugUI.fullgc() end
local rs=Engine.down("0")
if pressed("restart",rs) then G.load_level(G.level_i); return end
if G.state=="pause" then
if pressed("confirm",Engine.down("5","ENTER")) then
G.state="play"
elseif pressed("back",back) then
G.open_world_map(G.level_i)
end
return
end
if G.state=="clear" then
G.level_clear_timer=G.level_clear_timer+dt
if pressed("confirm",Engine.down("5","ENTER")) then
G.open_world_map(Save.data.last_level)
elseif pressed("restart",Engine.down("0")) then
G.load_level(G.level_i)
elseif pressed("back",back) then
G.open_world_map(G.level_i)
end
return
end
if G.state=="gameover" then
if pressed("confirm",Engine.down("5","ENTER")) then
G.load_level(G.level_i)
elseif pressed("back",back) then
G.open_world_map(G.level_i)
end
return
end
G.p.inv=math.max(0,G.p.inv-dt)
update_movers(dt)
move_player(dt)
update_boxes(dt)
update_enemies(dt)
update_boss(dt)
update_bs(dt)
triggers()
update_crumbles(dt)
local target=G.p.x-84
if target<0 then target=0 end
local max=math.max(0,G.st.width-240)
if target>max then target=max end
G.camera_x=G.camera_x+(target-G.camera_x)*math.min(1,6*dt)
G.gc_timer=G.gc_timer+dt
if G.gc_timer>1.5 then
G.gc_timer=0
DebugUI.gcstep()
end
end
function G.draw()
Render.draw(G)
end
function G.init()
Engine.init()
pcall(collectgarbage,"setpause",110)
pcall(collectgarbage,"setstepmul",400)
collectgarbage("collect")
Sprites.load()
Save.load()
G.level_i=math.min(Save.data.last_level,#StageData.stages)
G.map_level=G.level_i
G.state="splash"
G.splash_t=0
end
CatBoxRuntime = CatBoxRuntime or {}
CatBoxRuntime.booted = false
CatBoxRuntime.first_draw = false
local life = nil
if type(engine) == "table" then
life = engine
elseif type(mre) == "table" then
life = mre
end
local function boot()
if CatBoxRuntime.booted then return end
Engine.boot_log("LOAD ENTER")
Game.init()
CatBoxRuntime.booted = true
Engine.boot_log("LOAD OK")
end
function CatBoxRuntime.update(dt)
boot()
Game.update(dt or (1 / 15))
end
function CatBoxRuntime.draw()
boot()
if not CatBoxRuntime.first_draw then Engine.boot_log("DRAW1 ENTER") end
Game.draw()
Engine.draw_count = Engine.draw_count + 1
Engine.flush()
if not CatBoxRuntime.first_draw then
CatBoxRuntime.first_draw = true
Engine.boot_log("DRAW1 OK clear=" .. tostring(Engine.clear_count) .. " rect=" .. tostring(Engine.rect_count) .. " text=" .. tostring(Engine.text_count) .. " flush=" .. tostring(Engine.flush_count))
end
end
function CatBoxRuntime.keypressed(k)
boot()
Engine.key_down(k)
end
function CatBoxRuntime.keyreleased(k)
Engine.key_up(k)
end
if life then
Engine.boot_log("BIND engine lifecycle installed")
life.load = function() boot() end
life.update = function(dt) CatBoxRuntime.update(dt) end
life.draw = function() CatBoxRuntime.draw() end
life.keypressed = function(k) CatBoxRuntime.keypressed(k) end
life.keyreleased = function(k) CatBoxRuntime.keyreleased(k) end
life.pause = function() if CatBoxRuntime.booted and Game.state == "play" then Game.state = "pause" end end
life.resume = function() end
life.quit = function() if Save and Save.write then Save.write() end end
else
boot()
end
function update(dt) CatBoxRuntime.update(dt) end
function draw() CatBoxRuntime.draw() end
function key_down(k) CatBoxRuntime.keypressed(k) end
function key_up(k) CatBoxRuntime.keyreleased(k) end
function on_update(dt) CatBoxRuntime.update(dt) end
function on_draw() CatBoxRuntime.draw() end
function on_key_down(k) CatBoxRuntime.keypressed(k) end
function on_key_up(k) CatBoxRuntime.keyreleased(k) end
