"""e2e_chat_ai_agent.py — E2E tự động cho Chat AI agent trên dự án mẫu.

Không cần API key: AIRequestThread được thay bằng worker kịch bản 8 lượt,
trả lời MIXED định dạng (fenced JSON protocol + XML tool-call kiểu Gemini/Ling)
rồi chạy qua đúng máy chủ vòng lặp AIChatView thật trên project tạm:
agent phải tạo UI có nút nhấn / label / photo(image) / textbox / card,
sinh PNG thật, viết + sửa main.lua tự động (edit_auto), đọc PROBLEMS.
Nếu agent KHÔNG tương tác được với dự án, in chẩn đoán từng lượt.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
import time
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ["LUAS30_APPDATA"] = tempfile.mkdtemp(prefix="luas30_e2e_chat_")
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "studio"))

from PySide6.QtCore import QThread, Signal
from PySide6.QtWidgets import QApplication

app = QApplication(sys.argv)

import app.views.ai_chat_view as chat_module
from app.services.ai_change_service import AIChangeService

# ---- Ghép chuỗi tránh literal đóng tag trong nguồn test ---- 
AK = "<arg_key>"
KV = "<arg_value>"
EK = "</" + "arg_key>"
EV = "</" + "arg_value>"
CT = "</" + "tool_call>"


def xcall(opener: str, *pairs) -> str:
    body = "".join(AK + str(k) + EK + KV + str(v) + EV for k, v in pairs)
    return "<tool_call" + opener + ">" + body + CT


def fenced(payload: str) -> str:
    return "```luas30-tool\n" + payload + "\n```"


MAIN_LUA_V1 = """-- E2E demo app (generated by ChatAI agent)
local ui_ok = true

function draw()
  -- TODO: ve UI (button/label/photo/textbox/card)
  ui_ok = true
end

return { draw = draw }
"""

MAIN_LUA_FIX = """  ui.draw('main')
  ui_ok = true"""

# 8 lượt model — xen kẽ fenced JSON và XML để test CẢ HAI giao thức.
SCRIPT = [
    "Inspect first.\n" + fenced(
        '{"tool":"ui_design","args":{"op":"catalog"},"reason":"List component types"}'
    ) + "\n" + fenced(
        '{"tool":"asset","args":{"op":"make","kind":"solid","name":"photo_hero",'
        '"target":"sprites","width":56,"height":56,"color":"#35507a"},'
        '"reason":"Placeholder photo PNG"}'
    ),
    fenced('{"tool":"ui_design","args":{"op":"add_screen","id":"main"},"reason":"Main screen"}')
    + "\n" + xcall("=ui_design", ("op", "add_item"), ("screen", "main"), ("type", "button"),
                   ("name", "btn_ok"), ("x", "80"), ("y", "240"), ("w", "78"), ("h", "24"),
                   ("text", "OK"), ("reason", "Add the OK button")),
    xcall("", ("op", "add_item"), ("screen", "main"), ("type", "label"),
          ("name", "lbl_title"), ("x", "16"), ("y", "16"), ("w", "208"), ("h", "20"),
          ("text", "Xin chao S30"), ("reason", "Title label"))
    + "\n" + xcall("=ui_design", ("op", "add_item"), ("screen", "main"), ("type", "image"),
                   ("name", "img_photo"), ("x", "92"), ("y", "64"), ("w", "56"), ("h", "56"),
                   ("src", "assets/sprites/photo_hero.png"), ("reason", "Photo image"))
    + "\n<tool_call name=\"ui_design\">" + AK + "op" + EK + KV + "add_item" + EV
    + AK + "screen" + EK + KV + "main" + EV + AK + "type" + EK + KV + "textbox" + EV
    + AK + "name" + EK + KV + "txt_name" + EV + AK + "x" + EK + KV + "16" + EV
    + AK + "y" + EK + KV + "140" + EV + AK + "w" + EK + KV + "208" + EV
    + AK + "h" + EK + KV + "24" + EV + AK + "text" + EK + KV + "Nhap ten" + EV
    + AK + "reason" + EK + KV + "Textbox input" + EV + CT,
    fenced('{"tool":"ui_design","args":{"op":"add_item","screen":"main","type":"card",'
           '"name":"card_info","x":"16","y":"180","w":"208","h":"48","text":"Info card"},'
           '"reason":"Simple card"}'),
    xcall(' name="write_file"', ("path", "main.lua"), ("content", MAIN_LUA_V1),
          ("reason", "Create app entry with UI hooks")),
    "```luas30-edit\n" + json.dumps({
        "path": "main.lua",
        "find": "-- TODO: ve UI (button/label/photo/textbox/card)",
        "replace": MAIN_LUA_FIX,
        "reason": "Wire the designed UI into draw()",
    }, ensure_ascii=False) + "\n```",
    fenced('{"tool":"problems","args":{"op":"list"},"reason":"Verify no diagnostics left"}'),
    "Hoan tat: man hinh main co nut OK, label, anh photo, textbox va card; main.lua da duoc sua.",
]


class FakeThread(QThread):
    completed = Signal(str)
    failed = Signal(str)
    idx = 0
    prompts: list[str] = []

    def __init__(self, cfg, api_key, system_prompt, messages, parent=None):
        super().__init__(parent)
        self.messages = list(messages or [])

    def run(self):
        if self.isInterruptionRequested():
            return
        i = FakeThread.idx
        FakeThread.idx += 1
        FakeThread.prompts.append(str(self.messages[-1]["content"])[:400] if self.messages else "")
        if i >= len(SCRIPT):
            self.failed.emit("E2E script het luot tra loi (agent van muon goi them)")
            return
        self.completed.emit(SCRIPT[i])


chat_module.AIRequestThread = FakeThread
from app.views.ai_chat_view import AIChatView  # noqa: E402


project = Path(tempfile.mkdtemp(prefix="luas30_e2e_proj_"))
(project / "conf.lua").write_text("conf = {}\n", encoding="utf-8")

chat = AIChatView(ROOT)
chat.set_project_root(project)

change_service = AIChangeService()
applied_log: list[str] = []


def handle_changes(payload):
    """Sương năng y nhu MainWindow._prepare/_apply trong che do edit_auto."""
    data = payload if isinstance(payload, dict) else {"edits": payload}
    try:
        cs = change_service.prepare(project, data.get("edits") or [])
    except Exception as exc:
        chat.on_code_changes_failed(str(exc))
        return
    chat.on_code_changes_prepared(cs.summary())
    if bool(data.get("auto_apply")):
        applied, backup = change_service.apply(cs)
        files = [{"path": c.relative_path, "added": c.added_lines,
                  "removed": c.removed_lines} for c in cs.changes]
        applied_log.extend(c.relative_path for c in cs.changes)
        chat.on_code_changes_applied(
            [str(p) for p in applied], str(backup or ""), files=files)


chat.changes_proposed.connect(handle_changes)
chat.review_changes_requested.connect(lambda: None)

problems_calls: list[str] = []


def fake_problems(op: str = "list") -> str:
    problems_calls.append(op)
    if len(problems_calls) == 1:
        return "PROBLEMS (1 muc):\n- [ERROR] main.lua:5:1 — unexpected symbol near 'end'"
    return ""


chat.set_problems_provider(fake_problems)

QUESTION = ("Tao ung dung co nut nhan, text, photo, textbox va card don gian; "
            "sau do kiem tra loi va tu sua.")
chat._history.append({"role": "user", "content": QUESTION})
chat._last_question = QUESTION
chat._start_request(QUESTION)

deadline = time.time() + 30
while time.time() < deadline:
    app.processEvents()
    if FakeThread.idx >= len(SCRIPT) and not chat._agent_active and chat._worker is None:
        break
    time.sleep(0.01)
for _ in range(20):
    app.processEvents()
    time.sleep(0.01)


failures: list[str] = []


def diagnose() -> None:
    print("\n---- CHAN DOAN (agent khong tuong tac duoc voi du an?) ----")
    print(f"luot model da phat: {FakeThread.idx}/{len(SCRIPT)}")
    for i, item in enumerate(chat._history):
        role = str(item.get("role") or "")
        content = str(item.get("content") or "")
        if role == "user" and item.get("_internal"):
            print(f"[ket qua tool] {content[:200]}")
        elif role == "assistant":
            print(f"[luot {i}] {content[:160].strip()}")
    print("---------------------------------------------------------------")


def check(ok: bool, label: str) -> None:
    print(("  [OK  ] " if ok else "  [FAIL] ") + label)
    if not ok:
        failures.append(label)


print("\n-- Ket qua E2E Chat AI agent tren du an mau --")
check(FakeThread.idx == len(SCRIPT), f"du 8 luot model chay het ({FakeThread.idx})")

design_path = project / ".luas30" / "ui_design.json"
check(design_path.is_file(), ".luas30/ui_design.json duoc tao")
types: set[str] = set()
if design_path.is_file():
    design = json.loads(design_path.read_text(encoding="utf-8"))
    blob = json.dumps(design, ensure_ascii=False)
    for screen in design.get("screens") or []:
        for item in screen.get("items") or []:
            types.add(str(item.get("type")))
    check({"button", "label", "image", "textbox", "card"} <= types,
          f"UI du 5 loai thanh phan: {sorted(types)}")
    check("photo_hero.png" in blob, "item image tro van asset photo")
else:
    blob = ""

png = project / "assets" / "sprites" / "photo_hero.png"
check(png.is_file() and png.read_bytes()[:4] == b"\x89PNG", "PNG photo that duoc sinh")

main_lua = (project / "main.lua").read_text(encoding="utf-8") if (project / "main.lua").is_file() else ""
check("local ui_ok" in main_lua, "write_file XML da tao main.lua")
check("ui.draw('main')" in main_lua and "TODO" not in main_lua,
      "luas30-edit da sua noi dung main.lua")
check(sorted(applied_log) == ["main.lua", "main.lua"], "ca 2 dot sua deu duoc TU AP")
check(len(chat._change_cards) == 2, "2 card 'Da sua N tep' trong transcript")
check(problems_calls == ["list"], f"tool problems duoc goi {len(problems_calls)} lan")
tool_errors = [str(i.get("content") or "") for i in chat._history
               if "Tool error" in str(i.get("content") or "")]
check(not tool_errors, "khong co 'Tool error' nao" + (f": {tool_errors[0][:160]}" if tool_errors else ""))
check("Hoan tat" in chat.transcript.toPlainText(), "luot ket thuc xuat hien trong transcript")
check(not chat._agent_active, "vong lap agent dung dung luc")

if failures:
    diagnose()
    print("\n== KET QUA ==\nFAIL:")
    for e in failures:
        print(" -", e)
    raise SystemExit(1)
print("\n== KET QUA ==\nFAIL: khong co")
